(() => {
'use strict';
const S=window.JMShared,T=window.JMTankArt,F=window.JMWorld4Fighter;
if(!S||!T||!F) throw new Error('Badlands requires shared, tank, and World 4 fighter module');
const {W,H,GROUND,GRAVITY,TANK_HOME,MAX_PULL,clamp,pointerToWorld,updateCamera,updateJohnny}=S;
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),level=Number(document.getElementById('game-shell').dataset.level||1);
const CFG={
1:{title:'BREAKNECK DESCENT',tag:'PREDICT THE DASH',waves:[['basic','sprinter','basic','sprinter'],['sprinter','roller','sprinter','basic','sprinter'],['sprinter','sprinter','roller','chonker','sprinter']]},
2:{title:'DUST AND DISORDER',tag:'SEE THROUGH THE DUST',waves:[['dust','basic','sprinter','dust'],['dust','roller','sprinter','basic','dust'],['dust','sprinter','dust','chonker','roller','sprinter']]},
3:{title:'CANYON RUSH',tag:'USE THE WALLS',waves:[['wallrunner','sprinter','basic','wallrunner'],['wallrunner','roller','sprinter','wallrunner','dust'],['wallrunner','sprinter','chonker','wallrunner','roller','sprinter']]},
4:{title:'THE PROVING GROUNDS',tag:'BREAK THE RELAY',waves:[['relay','sprinter','basic','relay'],['relay','shield','sprinter','relay','roller'],['relay','sprinter','shield','chonker','relay','sprinter']]},
5:{title:'REDLINE FLATS',tag:'OUTRUN THE CHAIN',waves:[['slipstream','sprinter','relay','basic'],['slipstream','relay','sprinter','chonker','dust'],['slipstream','relay','sprinter','shield','chonker','wallrunner','sprinter']]}
}[level];
const $=id=>document.getElementById(id),scoreEl=$('score'),healthEl=$('health'),waveEl=$('wave'),remainEl=$('remaining'),speedEl=$('speed-threat'),chainEl=$('chain'),steroidButton=$('steroids'),steroidCountEl=$('steroid-count'),muteButton=$('mute'),titleScreen=$('title-screen'),gameOverScreen=$('game-over'),victoryScreen=$('mission-complete'),finalScoreEl=$('final-score'),toastEl=$('toast'),resultStarsEl=$('result-stars'),resultScoreEl=$('result-score'),resultCatsEl=$('result-cats'),resultSpeedEl=$('result-speed'),resultChainEl=$('result-chain'),resultDefenseEl=$('result-defense');
let last=performance.now(),running=false,over=false,done=false,score=0,health=5,wave=-1,spawned=0,resolved=0,queue=[],spawnTimer=0,between=0,elapsed=0,muted=false,audio=null,steroids=3,steroidTimer=0,cameraX=0,aim=null,shake=0,toastTimer=null,flattened=0,speedKills=0,chainBreaks=0,finishTimer=0;
const actors=[],clouds=[],particles=[],floaters=[],hero={armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0},tank={x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,resetTimer:0,bounced:false,hitIds:new Set(),wallBounces:0};
const terrainY=x=>{if(level===1)return GROUND-8-Math.sin(x*.006)*18+Math.max(0,x-500)*.035;if(level===3)return GROUND-15+Math.sin(x*.009)*8;return GROUND-8+Math.sin(x*.004)*5;};
const toast=(t,d=850)=>{toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),d)};
function beep(type='hit'){if(muted)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime,m={throw:[95,55,.1],hit:[80,45,.08],dash:[260,90,.1],hurt:[120,70,.2],win:[330,880,.45],power:[160,420,.25],chain:[520,220,.16]}[type]||[120,80,.1];o.frequency.setValueAtTime(m[0],n);o.frequency.exponentialRampToValueAtTime(m[1],n+m[2]);g.gain.setValueAtTime(.055,n);g.gain.exponentialRampToValueAtTime(.001,n+m[2]);o.connect(g).connect(audio.destination);o.start(n);o.stop(n+m[2]);}catch{}}
function hud(){scoreEl.textContent=String(score).padStart(6,'0');healthEl.textContent=Array.from({length:5},(_,i)=>i<health?'♥':'♡').join(' ');waveEl.textContent=`${Math.max(1,wave+1)}/3`;remainEl.textContent=wave<0?'INCOMING':String(Math.max(0,queue.length-resolved));speedEl.textContent=actors.some(a=>!a.dead&&(a.kind==='sprinter'||a.kind==='slipstream'||a.kind==='wallrunner'))?'HOT':'CLEAR';chainEl.textContent=actors.some(a=>!a.dead&&(a.boost>1.05||a.kind==='relay'))?'ACTIVE':'CLEAR';}
function impact(x,y,strong=false,c='#e8c28a'){for(let i=0;i<(strong?24:12);i++){let a=Math.random()*Math.PI*2,s=70+Math.random()*(strong?300:160);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-80,life:.35+Math.random()*.45,max:.8,size:2+Math.random()*8,c})}shake=Math.max(shake,strong?16:7)}
function resetTank(){Object.assign(tank,{x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,resetTimer:0,bounced:false,wallBounces:0});tank.hitIds.clear();aim=null;}
function actor(kind,index){const x=930+index*135+Math.random()*70,y=terrainY(x)-28;return{id:`${wave}-${index}-${Math.random()}`,kind,x,y,speed:kind==='sprinter'?68:kind==='wallrunner'?82:kind==='slipstream'?76:kind==='relay'?74:kind==='roller'?88:kind==='chonker'?48:58,boost:1,boostTimer:0,dead:false,phase:Math.random()*6.2,state:kind==='sprinter'?'ready':'run',timer:kind==='sprinter'?1+Math.random():kind==='relay'?1.5:0,hidden:false,wallTimer:0,dustTimer:kind==='dust'?1.1:0,tagged:false,scale:kind==='chonker'?1.45:1};}
function startWave(){wave++;queue=CFG.waves[wave].slice();spawned=0;resolved=0;spawnTimer=.25;between=0;finishTimer=0;toast(`WAVE ${wave+1}: ${CFG.tag}`,1100);hud();}
function kill(a,why){if(a.dead)return;a.dead=true;resolved++;flattened++;score+=why==='ricochet'?650:why==='chain'?550:350;if(['sprinter','wallrunner','slipstream','relay'].includes(a.kind))speedKills++;if(a.kind==='relay'||why==='chain')chainBreaks++;impact(a.x,a.y-10,true,why==='ricochet'?'#ffd26c':'#f2d29b');floaters.push({x:a.x,y:a.y-70,text:why==='ricochet'?'RICHOCHET!':why==='chain'?'CHAIN BREAK!':'WHAM!',life:.8});beep(a.kind==='relay'?'chain':'hit');hud();}
function hurt(t){if(over||done)return;health--;shake=20;impact(170,GROUND-85,true,'#ffb07a');toast(t,850);beep('hurt');hud();if(health<=0){running=false;over=true;finalScoreEl.textContent=`Score: ${score.toLocaleString()}`;gameOverScreen.classList.add('visible')}}
function spawn(){actors.push(actor(queue[spawned],spawned));spawned++;spawnTimer=.58+Math.random()*.2;}
function updateActor(a,dt){if(a.dead)return;a.phase+=dt*6;if(a.boostTimer>0){a.boostTimer-=dt;if(a.boostTimer<=0)a.boost=1}
if(a.kind==='sprinter'){a.timer-=dt;if(a.state==='ready'&&a.timer<=0){a.state='dash';a.timer=.5;toast('SPRINTER CAT DASHING!',450);beep('dash')}else if(a.state==='dash'){a.x-=a.speed*4.1*dt;if(a.timer<=0){a.state='ready';a.timer=.9+Math.random()*.8}}else a.x-=a.speed*.45*dt;}
else if(a.kind==='dust'){a.x-=a.speed*a.boost*dt;a.dustTimer-=dt;if(a.dustTimer<=0){clouds.push({x:a.x,y:a.y-20,r:42,life:2.2,max:2.2});a.dustTimer=1.25;}}
else if(a.kind==='wallrunner'){a.wallTimer+=dt;a.x-=a.speed*1.35*a.boost*dt;if(Math.sin(a.wallTimer*2.7)>.35)a.y=terrainY(a.x)-75-Math.abs(Math.sin(a.wallTimer*3))*105;else a.y=terrainY(a.x)-28;}
else if(a.kind==='relay'){a.x-=a.speed*a.boost*dt;a.timer-=dt;if(a.timer<=0){const target=actors.find(b=>!b.dead&&b!==a&&b.x<a.x&&a.x-b.x<230);if(target){target.boost=Math.max(target.boost,1.9);target.boostTimer=2.7;floaters.push({x:target.x,y:target.y-65,text:'RELAY BOOST!',life:.7});a.tagged=true;}a.timer=1.5;}}
else if(a.kind==='slipstream'){a.x-=a.speed*1.75*dt;for(const b of actors)if(!b.dead&&b!==a&&b.x>a.x&&b.x-a.x<260){b.boost=Math.max(b.boost,1.65);b.boostTimer=.35;}}
else if(a.kind==='roller'){a.speed=clamp(a.speed+26*dt,88,205);a.x-=a.speed*a.boost*dt;}
else a.x-=a.speed*a.boost*dt;
if(a.kind!=='wallrunner')a.y=terrainY(a.x)-28*a.scale;a.hidden=clouds.some(c=>Math.hypot(a.x-c.x,a.y-c.y)<c.r*.9);if(a.x<115){a.dead=true;resolved++;hurt(`${a.kind.toUpperCase()} CAT BROKE THROUGH!`);}}
function updateMission(dt){if(over||done)return;if(wave<0){between-=dt;if(between<=0)startWave();return;}if(spawned<queue.length){spawnTimer-=dt;if(spawnTimer<=0)spawn();return;}if(resolved<queue.length||actors.some(a=>!a.dead))return;if(wave<2){between+=dt;if(between>.9)startWave();return;}finishTimer+=dt;if(finishTimer>.8)complete();}
function held(){return !aim||tank.flying?{x:tank.x,y:tank.y}:{x:aim.x,y:Math.min(aim.y,GROUND-40)}}
function throwTank(){if(!aim||tank.flying||!running)return;const dx=tank.x-aim.x,dy=tank.y-aim.y,p=Math.hypot(dx,dy);if(p<18){aim=null;return}const sc=Math.min(p,MAX_PULL)/p,b=steroidTimer>0?1.42:1,h=held();Object.assign(tank,{x:h.x,y:h.y,vx:dx*sc*F.throwScale*b,vy:dy*sc*F.throwScale*b,angular:Math.min(9,2+p/55),flying:true,resetTimer:0,bounced:false,wallBounces:0});tank.hitIds.clear();aim=null;hero.releaseTimer=.28;beep('throw');}
function updateTank(dt){if(!tank.flying)return;tank.vy+=GRAVITY*F.gravityMultiplier*dt;tank.x+=tank.vx*dt;tank.y+=tank.vy*dt;tank.angle+=tank.angular*dt;if(level===3&&tank.wallBounces<2&&(tank.x>1280||tank.x<80)){tank.vx*=-.78;tank.wallBounces++;beep('hit');toast('CANYON RICOCHET!',450);}for(const a of actors){if(a.dead||tank.hitIds.has(a.id))continue;const r=(a.kind==='chonker'?68:46)+F.collisionBonus;if(Math.hypot(tank.x-a.x,tank.y-(a.y-4))<r){tank.hitIds.add(a.id);if(a.kind==='shield'&&!(tank.vy>0&&tank.y<a.y-35)){tank.vx*=-.28;tank.vy=-Math.abs(tank.vy)*.35-80;toast('SHIELD CAT! ARC IT!',500);continue}kill(a,level===3&&tank.wallBounces?'ricochet':a.kind==='relay'?'chain':'vehicle');tank.vx*=F.impactX;tank.vy*=F.impactY;}}const gy=terrainY(tank.x)-22;if(tank.y>=gy){tank.y=gy;if(Math.abs(tank.vy)>150&&!tank.bounced){tank.vy*=F.bounceY;tank.vx*=F.bounceX;tank.bounced=true;impact(tank.x,tank.y+8,false)}else{tank.vy=0;tank.vx*=Math.pow(.08,dt)}}if(tank.x<-450||tank.x>2100||(Math.abs(tank.vx)<12&&tank.y>=gy-1)){tank.resetTimer+=dt;if(tank.resetTimer>.55)resetTank()}else tank.resetTimer=0;}
function complete(){if(done)return;done=true;running=false;const stars=1+(health===5?1:0)+(speedKills>=3?1:0);resultStarsEl.textContent='★'.repeat(stars)+'☆'.repeat(3-stars);resultScoreEl.textContent=score.toLocaleString();resultCatsEl.textContent=flattened;resultSpeedEl.textContent=speedKills;resultChainEl.textContent=chainBreaks;resultDefenseEl.textContent=health===5?'UNTOUCHED':`${health}/5 HEARTS`;toast(`${CFG.title} SECURED`,1100);beep('win');setTimeout(()=>victoryScreen.classList.add('visible'),800);}
function reset(){running=true;over=false;done=false;score=0;health=5;wave=-1;spawned=resolved=0;queue=[];spawnTimer=0;between=.35;elapsed=0;steroids=3;steroidTimer=0;cameraX=0;aim=null;shake=0;flattened=speedKills=chainBreaks=0;finishTimer=0;actors.length=clouds.length=particles.length=floaters.length=0;Object.assign(hero,{armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0});resetTank();steroidButton.disabled=false;steroidCountEl.textContent='3 demo doses';hud();toast(CFG.title,900);}
function update(dt){if(!running){cameraX=updateCamera(cameraX,tank,aim,running,dt);updateJohnny(hero,tank,aim,running,dt);return}elapsed+=dt;if(steroidTimer>0)steroidTimer=Math.max(0,steroidTimer-dt);updateMission(dt);for(const a of actors)updateActor(a,dt);for(const c of clouds){c.life-=dt;c.r+=18*dt;c.x-=10*dt}for(let i=clouds.length-1;i>=0;i--)if(clouds[i].life<=0)clouds.splice(i,1);updateTank(dt);for(const p of particles){p.life-=dt;p.vy+=420*dt;p.x+=p.vx*dt;p.y+=p.vy*dt}for(const f of floaters){f.life-=dt;f.y-=42*dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1);shake*=Math.pow(.003,dt);cameraX=updateCamera(cameraX,tank,aim,running,dt);updateJohnny(hero,tank,aim,running,dt);hud();}
function drawBg(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,level===5?'#3a3952':'#6286a0');sky.addColorStop(.68,level===5?'#a06a58':'#e2b47e');sky.addColorStop(1,'#d79257');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#7c4c35';for(let i=-1;i<9;i++){let x=i*240-(cameraX*.08%240),h=80+((i*71)%120);ctx.beginPath();ctx.moveTo(x,GROUND);ctx.lineTo(x+70,GROUND-h);ctx.lineTo(x+160,GROUND-h*.78);ctx.lineTo(x+240,GROUND);ctx.closePath();ctx.fill()}ctx.fillStyle='#a7683e';ctx.fillRect(0,GROUND-25,W,25);if(level===4){ctx.fillStyle='#6e6e65';ctx.fillRect(0,GROUND-18,W,18);ctx.strokeStyle='#ddd19b';ctx.setLineDash([45,35]);ctx.beginPath();ctx.moveTo(0,GROUND-9);ctx.lineTo(W,GROUND-9);ctx.stroke();ctx.setLineDash([])}if(level===5){ctx.fillStyle='#49304f';for(let x=860;x<1500;x+=160){ctx.beginPath();ctx.moveTo(x,GROUND-20);ctx.lineTo(x+25,GROUND-95);ctx.lineTo(x+45,GROUND-20);ctx.fill()}}}
function drawActor(a){if(a.dead)return;ctx.save();ctx.translate(a.x,a.y);ctx.globalAlpha=a.hidden?.38:1;const c={basic:'#c58b5e',sprinter:'#e2b56c',dust:'#aa7b56',wallrunner:'#d29c66',relay:'#d7be51',slipstream:'#d87542',roller:'#9c6f53',chonker:'#8d6048',shield:'#b98a60'}[a.kind]||'#b9845d';ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(0,-25,30*a.scale,25*a.scale,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(18*a.scale,-50*a.scale,19*a.scale,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1d1714';ctx.beginPath();ctx.moveTo(6*a.scale,-64*a.scale);ctx.lineTo(12*a.scale,-84*a.scale);ctx.lineTo(21*a.scale,-65*a.scale);ctx.fill();ctx.beginPath();ctx.moveTo(25*a.scale,-64*a.scale);ctx.lineTo(34*a.scale,-82*a.scale);ctx.lineTo(40*a.scale,-60*a.scale);ctx.fill();if(a.kind==='sprinter'&&a.state==='ready'){ctx.strokeStyle='#fff1a1';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,-25,38,0,Math.PI*2);ctx.stroke()}if(a.kind==='relay'){ctx.fillStyle='#fff17a';ctx.fillRect(-22,-40,38,8)}if(a.kind==='slipstream'){ctx.strokeStyle='rgba(255,240,180,.55)';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(10,-35);ctx.lineTo(170,-35);ctx.stroke()}if(a.kind==='shield'){ctx.fillStyle='#6c7375';ctx.fillRect(-34,-72,18,70)}ctx.restore();}
function render(){ctx.clearRect(0,0,W,H);ctx.save();if(shake>.4)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawBg();ctx.save();ctx.translate(-cameraX,0);ctx.save();ctx.translate(24,3);ctx.translate(142,582);ctx.scale(.5,.5);ctx.translate(-142,-582);S.drawJohnny(ctx,hero,steroidTimer,elapsed);ctx.restore();for(const c of clouds){ctx.save();ctx.globalAlpha=.18*(c.life/c.max);ctx.fillStyle='#b98552';ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,Math.PI*2);ctx.fill();ctx.restore()}for(const a of actors)drawActor(a);if(!tank.flying&&aim){const h=held();T.drawTank(ctx,{...tank,x:h.x,y:h.y,angle:-.08})}else T.drawTank(ctx,tank);if(aim&&!tank.flying){ctx.strokeStyle='#ffcf33';ctx.lineWidth=4;ctx.setLineDash([10,8]);ctx.beginPath();ctx.moveTo(tank.x,tank.y);ctx.lineTo(aim.x,aim.y);ctx.stroke();ctx.setLineDash([])}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=Math.max(0,f.life);ctx.fillStyle='#fff0a3';ctx.font='900 24px Impact,system-ui';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;ctx.textAlign='left';ctx.restore();ctx.restore();}
function frame(now){const dt=Math.min((now-last)/1000,.033);last=now;update(dt);render();requestAnimationFrame(frame)}
canvas.addEventListener('pointerdown',e=>{if(!running||tank.flying)return;const p=pointerToWorld(canvas,e,cameraX);if(Math.hypot(p.x-tank.x,p.y-tank.y)<130){aim=p;canvas.setPointerCapture?.(e.pointerId)}});canvas.addEventListener('pointermove',e=>{if(!aim||tank.flying)return;const p=pointerToWorld(canvas,e,cameraX),dx=p.x-tank.x,dy=p.y-tank.y,l=Math.hypot(dx,dy);aim=l>MAX_PULL?{x:tank.x+dx/l*MAX_PULL,y:tank.y+dy/l*MAX_PULL}:p});canvas.addEventListener('pointerup',throwTank);canvas.addEventListener('pointercancel',()=>aim=null);
steroidButton.addEventListener('click',()=>{if(!running||steroids<=0)return;steroids--;steroidTimer=12;steroidCountEl.textContent=steroids===1?'1 demo dose':`${steroids} demo doses`;steroidButton.disabled=steroids<=0;toast('UNREGULATED STRENGTH!');beep('power')});muteButton.addEventListener('click',()=>{muted=!muted;muteButton.textContent=muted?'🔇':'🔊'});$('start').addEventListener('click',()=>{titleScreen.classList.remove('visible');reset()});$('restart').addEventListener('click',()=>{gameOverScreen.classList.remove('visible');reset()});$('replay').addEventListener('click',()=>{victoryScreen.classList.remove('visible');reset()});hud();render();requestAnimationFrame(frame);
})();