(() => {
'use strict';
const S=window.JMShared,T=window.JMTankArt,F=window.JMWorld4Fighter,E=window.JMEnemyArt;
if(!S||!T||!F||!E) throw new Error('Boss 6 requires shared, tank, fighter, and enemy art modules');
const {W,H,GROUND,GRAVITY,TANK_HOME,MAX_PULL,clamp,pointerToWorld,updateCamera,updateJohnny}=S;
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);
const scoreEl=$('score'),healthEl=$('health'),hpEl=$('boss-hp'),controlEl=$('control-status'),nodeEl=$('nodes'),steroidButton=$('steroids'),steroidCountEl=$('steroid-count'),muteButton=$('mute'),titleScreen=$('title-screen'),overScreen=$('game-over'),winScreen=$('mission-complete'),finalScoreEl=$('final-score'),toastEl=$('toast'),rStars=$('result-stars'),rScore=$('result-score'),rHits=$('result-hits'),rNodes=$('result-nodes'),rSnare=$('result-snare'),rDefense=$('result-defense');
const MAX_HP=15;
let last=performance.now(),running=false,over=false,win=false,score=0,health=5,hp=MAX_HP,phase=1,elapsed=0,steroids=3,steroidTimer=0,muted=false,audio=null,aim=null,cameraX=0,shake=0,toastTimer=null,hits=0,nodesBroken=0,snareReturns=0,attackClock=4.2,attackState='idle',attackTimer=0,minionClock=4.5,shieldOpen=0,snareReady=0,snared=false,snareTimer=0;
const particles=[],floaters=[],minions=[];
const hero={armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0};
const tank={x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,ready:true,resetTimer:0,bounced:false,hitBoss:false,snareReturn:false,hitIds:new Set()};
const theresa={x:1080,y:GROUND-48,hitFlash:0,merge:0};
const nodes=[{dx:-195,dy:-75,alive:true,pulse:0},{dx:-165,dy:-165,alive:true,pulse:1.8},{dx:-125,dy:-210,alive:true,pulse:3.6}];
function toast(t,d=900){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),d)}
function beep(type='hit'){if(muted)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime,m={throw:[96,52,.1],hit:[75,42,.1],node:[380,120,.15],warning:[180,320,.22],snare:[110,55,.22],catch:[220,700,.2],hurt:[120,70,.22],win:[330,930,.5],power:[160,420,.25]}[type]||[120,80,.1];o.type=type==='snare'?'sawtooth':'square';o.frequency.setValueAtTime(m[0],n);o.frequency.exponentialRampToValueAtTime(m[1],n+m[2]);g.gain.setValueAtTime(.055,n);g.gain.exponentialRampToValueAtTime(.001,n+m[2]);o.connect(g).connect(audio.destination);o.start(n);o.stop(n+m[2])}catch{}}
function impact(x,y,strong=false,c='#d47bea'){for(let i=0;i<(strong?28:13);i++){const a=Math.random()*Math.PI*2,s=70+Math.random()*(strong?320:160);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-90,life:.4+Math.random()*.4,max:.8,size:3+Math.random()*8,c})}shake=Math.max(shake,strong?19:8)}
function activeNodes(){return nodes.filter(n=>n.alive).length}
function phaseFor(){return hp>10?1:hp>5?2:3}
function hud(){scoreEl.textContent=String(score).padStart(6,'0');healthEl.textContent=Array.from({length:5},(_,i)=>i<health?'♥':'♡').join(' ');hpEl.textContent='■'.repeat(hp)+'□'.repeat(MAX_HP-hp);controlEl.textContent=phase===3?(snared?'TANK SNARED':'MERGED'):activeNodes()?'SHIELDED':'EXPOSED';nodeEl.textContent=phase===3?'MELTED':String(activeNodes())}
function resetTank(ready=true){snared=false;snareTimer=0;Object.assign(tank,{x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,ready,resetTimer:0,bounced:false,hitBoss:false,snareReturn:false});tank.hitIds.clear();aim=null;hero.catchPose=0}
function regenerateNodes(count=3){for(let i=0;i<nodes.length;i++)nodes[i].alive=i<count;shieldOpen=0;hud()}
function hurt(t){if(over||win)return;health--;shake=20;impact(170,GROUND-88,true,'#ffab78');toast(t,900);beep('hurt');hud();if(health<=0){running=false;over=true;finalScoreEl.textContent=`Theresa HP: ${hp}/${MAX_HP} · Nodes broken: ${nodesBroken}`;overScreen.classList.add('visible')}}
function damageTheresa(n,label){if(win)return;hp=Math.max(0,hp-n);hits++;score+=800*n*phase;theresa.hitFlash=.25;impact(theresa.x,theresa.y-115,true,'#ffe27a');floaters.push({x:theresa.x,y:theresa.y-180,text:`${label} -${n}`,life:.9});beep('hit');const old=phase;phase=phaseFor();if(phase!==old){if(phase===2){toast('THERESA: EVOLVE THE FRONT!',1500);regenerateNodes(2)}if(phase===3){toast('THERESA IS MERGING WITH THE INFESTATION!',1800);for(const n of nodes)n.alive=false;theresa.merge=1;snareReady=1.2;beep('warning')}}hud();if(hp<=0)finishWin()}
function breakNode(n){if(!n.alive)return;n.alive=false;nodesBroken++;score+=350;impact(theresa.x+n.dx,theresa.y+n.dy,true,'#f0a2ff');floaters.push({x:theresa.x+n.dx,y:theresa.y+n.dy-35,text:'NODE BROKEN!',life:.75});beep('node');if(activeNodes()===0){shieldOpen=phase===1?2.2:1.7;toast('LIVING SHIELD DOWN! HIT THERESA!',900)}hud()}
function spawnMinion(kind=Math.random()<.3?'controller':'alienling'){minions.push({id:`m-${Math.random()}`,kind,x:980+Math.random()*220,y:GROUND-32,speed:kind==='controller'?42:62,scale:kind==='controller'?.9:.78,phase:Math.random()*6.2,dead:false,link:false})}
function updateMinions(dt){if(phase<2)return;minionClock-=dt;if(minionClock<=0&&minions.filter(m=>!m.dead).length<3){spawnMinion();minionClock=phase===2?4.3:3.3}const controller=minions.find(m=>!m.dead&&m.kind==='controller');for(const m of minions){if(m.dead)continue;m.phase+=dt*5;m.link=!!controller&&controller!==m;m.x-=m.speed*(m.link?1.45:1)*dt;m.y=GROUND-32*m.scale;if(m.x<118){m.dead=true;hurt('ALIEN MINION BROKE THROUGH!')}}}
function startAttack(){attackState='warning';attackTimer=phase===1?1.35:.8;toast(phase===1?'THERESA IS AIMING THE LIVING GROUND!':'THERESA IS COMMANDING A TENDRIL STRIKE!',phase===1?1200:900);beep('warning')}
function updateAttack(dt){if(phase===3)return;if(attackState==='warning'){attackTimer-=dt;if(attackTimer<=0){attackState='idle';attackClock=phase===1?4.5:2.15;hurt('THERESA STRUCK THROUGH THE GROUND!')}return}attackClock-=dt;if(attackClock<=0)startAttack()}
function captureTank(){snared=true;snareTimer=2.8;Object.assign(tank,{x:690,y:260,vx:0,vy:0,angle:-.18,angular:0,flying:false,ready:true,resetTimer:0,bounced:false,hitBoss:false,snareReturn:false});aim=null;hero.catchPose=.1;toast('THERESA CAUGHT THE TANK! GRAB IT AND RIP IT FREE!',1500);beep('snare');hud()}
function updateSnare(dt){if(phase!==3)return;if(snared){snareTimer-=dt;if(snareTimer<=0){hurt('THERESA RIPPED THE TANK AWAY!');resetTank(true);snareReady=2.5}return}snareReady-=dt;if(snareReady<=0&&tank.flying&&tank.x>500&&tank.x<900&&tank.y<GROUND-75){captureTank();snareReady=4.6}}
function held(){return !aim||tank.flying?{x:tank.x,y:tank.y}:{x:aim.x,y:Math.min(aim.y,GROUND-40)}}
function throwTank(){if(!aim||tank.flying||!tank.ready||!running)return;const dx=tank.x-aim.x,dy=tank.y-aim.y,p=Math.hypot(dx,dy);if(p<18){aim=null;return}const sc=Math.min(p,MAX_PULL)/p,b=steroidTimer>0?1.42:1,h=held(),wasSnared=snared;snared=false;Object.assign(tank,{x:h.x,y:h.y,vx:dx*sc*F.throwScale*b*(wasSnared?1.08:1),vy:dy*sc*F.throwScale*b*(wasSnared?1.08:1),angular:Math.min(9,2+p/55),flying:true,ready:false,resetTimer:0,bounced:false,hitBoss:false,snareReturn:wasSnared});tank.hitIds.clear();aim=null;hero.releaseTimer=.28;if(wasSnared){snareReturns++;score+=300;toast('TENDRIL BROKEN! RETURN IT!',700);beep('catch')}else beep('throw');hud()}
function updateTank(dt){if(!tank.flying)return;tank.vy+=GRAVITY*F.gravityMultiplier*dt;tank.x+=tank.vx*dt;tank.y+=tank.vy*dt;tank.angle+=tank.angular*dt;
for(const n of nodes){if(!n.alive)continue;const nx=theresa.x+n.dx,ny=theresa.y+n.dy;if(Math.hypot(tank.x-nx,tank.y-ny)<62+F.collisionBonus){breakNode(n);tank.vx*=.68;tank.vy*=.72;tank.hitIds.add(`node-${n.dx}`);break}}
for(const m of minions){if(m.dead||tank.hitIds.has(m.id))continue;if(Math.hypot(tank.x-m.x,tank.y-(m.y-5))<48+F.collisionBonus){m.dead=true;score+=m.kind==='controller'?500:300;impact(m.x,m.y-15,true,m.kind==='controller'?'#ffe273':'#ca79e8');floaters.push({x:m.x,y:m.y-65,text:m.kind==='controller'?'LINK BROKEN!':'WHAM!',life:.7});tank.hitIds.add(m.id);tank.vx*=F.impactX;tank.vy*=F.impactY}}
if(!tank.hitBoss&&Math.hypot(tank.x-theresa.x,tank.y-(theresa.y-110))<125+F.collisionBonus){tank.hitBoss=true;const exposed=phase===3||activeNodes()===0;if(exposed){damageTheresa(tank.snareReturn?2:1,tank.snareReturn?'RECLAIMED TANK':'DIRECT HIT');if(phase<3)shieldOpen=Math.max(0,shieldOpen-.45);tank.vx*=F.impactX;tank.vy*=F.impactY}else{toast('LIVING SHIELD! BREAK THE GLOWING NODES!',650);tank.vx*=-.25;tank.vy=-Math.abs(tank.vy)*.28-80}}
if(tank.y>=GROUND-22){tank.y=GROUND-22;if(Math.abs(tank.vy)>150&&!tank.bounced){tank.vy*=F.bounceY;tank.vx*=F.bounceX;tank.bounced=true;impact(tank.x,tank.y+8)}else{tank.vy=0;tank.vx*=Math.pow(.07,dt)}}if(tank.x<-450||tank.x>2200||(tank.y>=GROUND-23&&Math.abs(tank.vx)<13)){tank.resetTimer+=dt;if(tank.resetTimer>.58)resetTank(true)}else tank.resetTimer=0}
function updateShield(dt){if(phase===3)return;if(activeNodes()===0){shieldOpen-=dt;if(shieldOpen<=0)regenerateNodes(phase===1?3:2)}for(const n of nodes)n.pulse+=dt*4}
function finishWin(){if(win)return;win=true;running=false;aim=null;snared=false;toast('GENERAL THERESA HAS LOST CONTROL OF THE INFESTATION!',1700);beep('win');const stars=1+(nodesBroken>=5?1:0)+(health===5?1:0);rStars.textContent='★'.repeat(stars)+'☆'.repeat(3-stars);rScore.textContent=score.toLocaleString();rHits.textContent=hits;rNodes.textContent=nodesBroken;rSnare.textContent=snareReturns;rDefense.textContent=health===5?'UNTOUCHED':`${health}/5 HEARTS`;setTimeout(()=>winScreen.classList.add('visible'),900)}
function reset(){running=true;over=win=false;score=0;health=5;hp=MAX_HP;phase=1;elapsed=0;steroids=3;steroidTimer=0;aim=null;cameraX=0;shake=0;hits=nodesBroken=snareReturns=0;attackClock=4.2;attackState='idle';attackTimer=0;minionClock=4.5;shieldOpen=0;snareReady=0;snared=false;snareTimer=0;particles.length=floaters.length=minions.length=0;theresa.hitFlash=0;theresa.merge=0;regenerateNodes(3);Object.assign(hero,{armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0});resetTank(true);steroidButton.disabled=false;steroidCountEl.textContent='3 demo doses';hud();toast('PHASE 1: ALL 3 NODES ARE ON THE NEAR SIDE — NO BANK SHOT REQUIRED!',2100)}
function update(dt){if(!running){cameraX=updateCamera(cameraX,tank,aim,running,dt);updateJohnny(hero,tank,aim,running,dt);return}elapsed+=dt;theresa.hitFlash=Math.max(0,theresa.hitFlash-dt);if(steroidTimer>0)steroidTimer=Math.max(0,steroidTimer-dt);updateShield(dt);updateAttack(dt);updateMinions(dt);updateSnare(dt);updateTank(dt);for(const p of particles){p.life-=dt;p.vy+=420*dt;p.x+=p.vx*dt;p.y+=p.vy*dt}for(const f of floaters){f.life-=dt;f.y-=45*dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1);shake*=Math.pow(.002,dt);cameraX=updateCamera(cameraX,tank,aim,running,dt);if(snared&&!aim)hero.catchPose=Math.max(hero.catchPose,.08);updateJohnny(hero,tank,aim,running,dt);hud()}
function drawBg(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#252337');sky.addColorStop(.58,'#5b405d');sky.addColorStop(1,'#a56b77');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#3f3745';for(let x=-80;x<W+220;x+=220){ctx.beginPath();ctx.moveTo(x,GROUND);ctx.lineTo(x+65,GROUND-140);ctx.lineTo(x+150,GROUND-95);ctx.lineTo(x+220,GROUND);ctx.closePath();ctx.fill()}ctx.fillStyle='#553e58';ctx.fillRect(0,GROUND-28,W,28);ctx.fillStyle='#713c78';for(let x=450;x<1500;x+=145){ctx.beginPath();ctx.moveTo(x,GROUND-28);ctx.lineTo(x+18,GROUND-115);ctx.lineTo(x+34,GROUND-28);ctx.fill()}ctx.save();ctx.globalAlpha=.4;ctx.fillStyle='#bd74d1';ctx.beginPath();ctx.ellipse(1080,GROUND-110,235,130,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawNode(n){if(!n.alive)return;const x=theresa.x+n.dx,y=theresa.y+n.dy,r=17+Math.sin(n.pulse)*2;ctx.save();ctx.strokeStyle='rgba(238,140,255,.42)';ctx.lineWidth=4;ctx.setLineDash([7,8]);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(theresa.x,theresa.y-110);ctx.stroke();ctx.setLineDash([]);ctx.shadowColor='#ee8cff';ctx.shadowBlur=24;ctx.fillStyle='#bd61d3';ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#fff0ff';ctx.lineWidth=4;ctx.stroke();ctx.globalAlpha=.68;ctx.strokeStyle='#f4b8ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,r+10,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawTheresa(){ctx.save();ctx.translate(theresa.x,theresa.y);ctx.scale(1.6+(phase===3?.13:0),1.6+(phase===3?.13:0));const fur=theresa.hitFlash>0?'#fff0c7':'#c58b5d',dark='#4a322b',stripe='#4a263d';ctx.strokeStyle=dark;ctx.lineWidth=11;ctx.beginPath();ctx.moveTo(30,-40);ctx.quadraticCurveTo(78,-58,88,-15);ctx.stroke();ctx.fillStyle=fur;ctx.strokeStyle=dark;ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,-72,52,47,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(-4,-145,42,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=fur;ctx.beginPath();ctx.moveTo(-37,-166);ctx.lineTo(-31,-194);ctx.lineTo(-13,-166);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(18,-166);ctx.lineTo(38,-191);ctx.lineTo(39,-157);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle=stripe;ctx.lineWidth=7;for(const y of [-98,-76,-54]){ctx.beginPath();ctx.moveTo(-42,y);ctx.lineTo(-18,y+10);ctx.stroke();ctx.beginPath();ctx.moveTo(42,y);ctx.lineTo(18,y+10);ctx.stroke()}ctx.fillStyle='#b7ff63';ctx.shadowColor='#b7ff63';ctx.shadowBlur=10;ctx.beginPath();ctx.ellipse(-16,-149,6,4,0,0,Math.PI*2);ctx.ellipse(12,-149,6,4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#5a274d';ctx.beginPath();ctx.arc(22,-112,8,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(-12,-82,7,0,Math.PI*2);ctx.fill();if(phase===3){ctx.strokeStyle='#a555b6';ctx.lineWidth=9;for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(-25+i*18,-85);ctx.quadraticCurveTo(-70+i*40,-145,-58+i*45,-215);ctx.stroke()}ctx.fillStyle='#d06ce4';ctx.beginPath();ctx.arc(5,-110,12,0,Math.PI*2);ctx.fill()}ctx.restore();if(phase<3&&activeNodes()>0){ctx.save();ctx.globalAlpha=.25;ctx.strokeStyle='#e89cff';ctx.lineWidth=8;ctx.beginPath();ctx.ellipse(theresa.x,theresa.y-110,140,170,0,0,Math.PI*2);ctx.stroke();ctx.restore()}}
function drawTrajectoryPreview(){if(!aim||tank.flying)return;const dx=tank.x-aim.x,dy=tank.y-aim.y,p=Math.hypot(dx,dy);if(p<1)return;const sc=Math.min(p,MAX_PULL)/p,b=steroidTimer>0?1.42:1,h=held(),boost=snared?1.08:1,vx=dx*sc*F.throwScale*b*boost,vy=dy*sc*F.throwScale*b*boost,g=GRAVITY*F.gravityMultiplier;ctx.save();ctx.strokeStyle=snared?'#f18cff':'#ffcf33';ctx.lineWidth=3;ctx.setLineDash([7,7]);ctx.beginPath();ctx.moveTo(h.x,h.y);let lastX=h.x,lastY=h.y;for(let i=1;i<=34;i++){const t=i*.07,x=h.x+vx*t,y=h.y+vy*t+.5*g*t*t;if(x<-450||x>2200||y>GROUND-22)break;ctx.lineTo(x,y);lastX=x;lastY=y}ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(lastX,lastY,7,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawMinion(m){if(m.dead)return;ctx.save();ctx.translate(m.x,m.y);ctx.scale(m.scale,m.scale);if(m.link){ctx.strokeStyle='#ffe469';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,-8,43,0,Math.PI*2);ctx.stroke()}E.drawGround(ctx,{phase:m.phase,windup:m.kind==='controller'});if(m.kind==='controller'){ctx.fillStyle='#d8a8ec';ctx.beginPath();ctx.ellipse(-16,-48,27,18,0,Math.PI,Math.PI*2);ctx.fill()}ctx.restore()}
function render(){ctx.clearRect(0,0,W,H);ctx.save();if(shake>.4)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawBg();ctx.save();ctx.translate(-cameraX,0);ctx.save();ctx.translate(24,3);ctx.translate(142,582);ctx.scale(.5,.5);ctx.translate(-142,-582);S.drawJohnny(ctx,hero,steroidTimer,elapsed);ctx.restore();for(const m of minions)drawMinion(m);drawTheresa();for(const n of nodes)drawNode(n);if(snared){ctx.strokeStyle='#c45edc';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(theresa.x-35,theresa.y-90);ctx.quadraticCurveTo(860,170,tank.x,tank.y);ctx.stroke()}if(!tank.flying&&aim){const h=held();T.drawTank(ctx,{...tank,x:h.x,y:h.y,angle:-.08})}else T.drawTank(ctx,tank);drawTrajectoryPreview();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=Math.max(0,f.life);ctx.fillStyle='#fff0a3';ctx.font='900 24px Impact,system-ui';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;ctx.restore();ctx.restore()}
function frame(now){const dt=Math.min((now-last)/1000,.033);last=now;update(dt);render();requestAnimationFrame(frame)}
canvas.addEventListener('pointerdown',e=>{if(!running||tank.flying)return;const p=pointerToWorld(canvas,e,cameraX);if(Math.hypot(p.x-tank.x,p.y-tank.y)<140){aim=p;canvas.setPointerCapture?.(e.pointerId)}});
canvas.addEventListener('pointermove',e=>{if(!aim||tank.flying)return;const p=pointerToWorld(canvas,e,cameraX),dx=p.x-tank.x,dy=p.y-tank.y,l=Math.hypot(dx,dy);aim=l>MAX_PULL?{x:tank.x+dx/l*MAX_PULL,y:tank.y+dy/l*MAX_PULL}:p});
canvas.addEventListener('pointerup',throwTank);canvas.addEventListener('pointercancel',()=>aim=null);
steroidButton.addEventListener('click',()=>{if(!running||steroids<=0)return;steroids--;steroidTimer=12;steroidCountEl.textContent=steroids===1?'1 demo dose':`${steroids} demo doses`;steroidButton.disabled=steroids<=0;toast('UNREGULATED STRENGTH!');beep('power')});
muteButton.addEventListener('click',()=>{muted=!muted;muteButton.textContent=muted?'🔇':'🔊'});
$('start').addEventListener('click',()=>{titleScreen.classList.remove('visible');reset()});
$('restart').addEventListener('click',()=>{overScreen.classList.remove('visible');reset()});
$('replay').addEventListener('click',()=>{winScreen.classList.remove('visible');reset()});
hud();render();requestAnimationFrame(frame);
})();