(() => {
'use strict';
const S=window.JMShared,T=window.JMTankArt,F=window.JMWorld4Fighter;
if(!S||!T||!F) throw new Error('Boss 5 requires shared, tank, and World 4 fighter module');
const {W,H,GROUND,GRAVITY,TANK_HOME,MAX_PULL,clamp,pointerToWorld,updateCamera,updateJohnny}=S,canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);
const scoreEl=$('score'),healthEl=$('health'),hpEl=$('boss-hp'),speedEl=$('speed-status'),catchEl=$('catches'),steroidButton=$('steroids'),steroidCountEl=$('steroid-count'),muteButton=$('mute'),titleScreen=$('title-screen'),overScreen=$('game-over'),winScreen=$('mission-complete'),finalScoreEl=$('final-score'),toastEl=$('toast'),starsEl=$('result-stars'),rScore=$('result-score'),rHits=$('result-hits'),rCatches=$('result-catches'),rDodges=$('result-dodges'),rDefense=$('result-defense');
const MAX_HP=12,CATCH_POINT={x:205,y:GROUND-120},CATCH_START=180,CATCH_SECURE=112,CATCH_HOLD=.16,CAUGHT_POS={x:235,y:GROUND-180};
let last=performance.now(),running=false,over=false,win=false,score=0,health=5,hp=MAX_HP,phase=1,elapsed=0,steroids=3,steroidTimer=0,muted=false,audio=null,aim=null,cameraX=0,shake=0,toastTimer=null,hits=0,catches=0,misses=0,dodges=0,attackClock=1.8,catchHolding=false,catchPointer=null,caughtTank=false;
const particles=[],floaters=[],afterimages=[],hero={armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0},tank={x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,ready:true,resetTimer:0,bounced:false,hitCarl:false,returned:false};
const carl={x:1080,y:GROUND-43,side:1,state:'idle',timer:1.3,fromX:1080,toX:1080,progress:0,exposed:false,hitFlash:0,fake:false};
const incoming={active:false,x:0,y:0,startX:0,startY:0,targetX:CATCH_POINT.x,targetY:GROUND-95,t:0,duration:.8,angle:0,hold:0};
const incomingInWindow=()=>incoming.active&&Math.hypot(incoming.x-CATCH_POINT.x,incoming.y-CATCH_POINT.y)<=CATCH_START;
window.JMShouldBypassGrabProxy=p=>incomingInWindow()&&Math.hypot(p.x-incoming.x,p.y-incoming.y)<135;
function toast(t,d=900){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),d)}
function beep(type='hit'){if(muted)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime,m={throw:[100,52,.11],hit:[78,42,.1],dash:[520,110,.14],catch:[220,720,.2],hurt:[120,70,.22],win:[330,900,.5],warning:[190,310,.22],power:[160,420,.25]}[type]||[120,80,.1];o.type=type==='dash'?'sawtooth':'square';o.frequency.setValueAtTime(m[0],n);o.frequency.exponentialRampToValueAtTime(m[1],n+m[2]);g.gain.setValueAtTime(.06,n);g.gain.exponentialRampToValueAtTime(.001,n+m[2]);o.connect(g).connect(audio.destination);o.start(n);o.stop(n+m[2])}catch{}}
function hud(){scoreEl.textContent=String(score).padStart(6,'0');healthEl.textContent=Array.from({length:5},(_,i)=>i<health?'♥':'♡').join(' ');hpEl.textContent='■'.repeat(hp)+'□'.repeat(MAX_HP-hp);speedEl.textContent=carl.state==='dash'?'UNREASONABLE':carl.exposed?'STOPPED':'FAST';catchEl.textContent=String(catches)}
function impact(x,y,strong=false,c='#f2ce91'){for(let i=0;i<(strong?28:13);i++){const a=Math.random()*Math.PI*2,s=70+Math.random()*(strong?330:160);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-90,life:.4+Math.random()*.4,max:.8,size:3+Math.random()*9,c})}shake=Math.max(shake,strong?19:8)}
function phaseFor(){return hp>8?1:hp>4?2:3}
function resetTank(ready=true){caughtTank=false;Object.assign(tank,{x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,ready,resetTimer:0,bounced:false,hitCarl:false,returned:false});aim=null;hero.releaseTimer=0}
function holdCaught(){caughtTank=true;Object.assign(tank,{x:CAUGHT_POS.x,y:CAUGHT_POS.y,vx:0,vy:0,angle:-.08,angular:0,flying:false,ready:true,resetTimer:0,bounced:false,hitCarl:false,returned:false});aim=null;hero.catchPose=.2}
function hurt(t){if(over||win)return;health--;shake=20;impact(175,GROUND-90,true,'#ffaf78');toast(t,900);beep('hurt');hud();if(health<=0){running=false;over=true;finalScoreEl.textContent=`Carl HP: ${hp}/${MAX_HP} · Catches: ${catches} · Missed: ${misses}`;overScreen.classList.add('visible')}}
function damageCarl(n,label){if(win)return;hp=Math.max(0,hp-n);hits++;score+=600*n*phase;carl.hitFlash=.24;impact(carl.x,carl.y-85,true,'#ffe278');floaters.push({x:carl.x,y:carl.y-145,text:`${label} -${n}`,life:.9});beep('hit');const old=phase;phase=phaseFor();if(phase!==old){if(phase===2)toast('COLONEL CARL: FLANKING SPEED!',1300);if(phase===3){toast('COLONEL CARL IS ACHIEVING UNREASONABLE VELOCITY',1800);beep('warning')}}hud();if(hp<=0)finishWin()}
function startDash(){carl.side*=-1;carl.fromX=carl.x;carl.toX=carl.side<0?62:1185;carl.progress=0;carl.state='dash';carl.exposed=false;carl.fake=phase===3&&Math.random()<.34;carl.timer=phase===1?.48:phase===2?.34:.24;beep('dash')}
function finishDash(){carl.x=carl.toX;if(phase===1){carl.state='recover';carl.exposed=true;carl.timer=.95;toast('CARL STOPPED! HIT HIM!',500);return}if(carl.fake){dodges++;carl.state='recover';carl.exposed=true;carl.timer=.48;toast('AFTERIMAGE! CARL FAKED THE THROW!',550);return}spawnIncoming();carl.state='recover';carl.exposed=true;carl.timer=phase===2?1.05:.72}
function spawnIncoming(){incoming.active=true;incoming.startX=carl.x;incoming.startY=GROUND-138;incoming.x=incoming.startX;incoming.y=incoming.startY;incoming.t=0;incoming.duration=phase===2?.83:.64;incoming.angle=0;incoming.hold=0;catchHolding=false;catchPointer=null;toast('CATCH THE TANK! (tap and hold it as it comes to you)',phase===2?1300:900);beep('throw')}
function catchIncoming(){incoming.active=false;catchHolding=false;catchPointer=null;catches++;score+=350;holdCaught();toast('CAUGHT! RETURN TO SENDER!',900);beep('catch');hud()}
function missIncoming(){incoming.active=false;catchHolding=false;catchPointer=null;misses++;hurt('CARL THREW A TANK THROUGH YOUR ZIP CODE!')}
function updateIncoming(dt){if(!incoming.active)return;incoming.t+=dt/incoming.duration;const t=clamp(incoming.t,0,1),ease=t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;incoming.x=incoming.startX+(incoming.targetX-incoming.startX)*ease;incoming.y=incoming.startY+(incoming.targetY-incoming.startY)*t-Math.sin(Math.PI*t)*115;incoming.angle+=(incoming.startX>incoming.targetX?-1:1)*dt*7;if(catchHolding){const d=Math.hypot(incoming.x-CATCH_POINT.x,incoming.y-CATCH_POINT.y);incoming.hold+=dt;if(incoming.hold>=CATCH_HOLD&&d<=CATCH_SECURE){incoming.hold=0;catchIncoming();return}}else incoming.hold=0;if(incoming.t>=1)missIncoming()}
function updateCarl(dt){if(win||over)return;carl.hitFlash=Math.max(0,carl.hitFlash-dt);if(carl.state==='dash'){const dur=carl.timer;carl.progress+=dt/dur;const t=clamp(carl.progress,0,1),e=t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;carl.x=carl.fromX+(carl.toX-carl.fromX)*e;afterimages.push({x:carl.x,y:carl.y,life:.16,max:.16});if(carl.progress>=1)finishDash();return}if(carl.state==='recover'){carl.timer-=dt;if(carl.timer<=0){carl.exposed=false;carl.state='idle';attackClock=phase===1?1.05:phase===2?.72:.45}return}attackClock-=dt;if(attackClock<=0&&!incoming.active)startDash()}
function held(){return !aim||tank.flying?{x:tank.x,y:tank.y}:{x:aim.x,y:Math.min(aim.y,GROUND-40)}}
function throwTank(){if(!aim||tank.flying||!tank.ready||!running)return;const dx=tank.x-aim.x,dy=tank.y-aim.y,p=Math.hypot(dx,dy);if(p<18){aim=null;return}const sc=Math.min(p,MAX_PULL)/p,b=steroidTimer>0?1.42:1,h=held(),returned=caughtTank;caughtTank=false;Object.assign(tank,{x:h.x,y:h.y,vx:dx*sc*F.throwScale*b,vy:dy*sc*F.throwScale*b,angular:Math.min(9,2+p/55),flying:true,ready:false,resetTimer:0,bounced:false,hitCarl:false,returned});aim=null;hero.releaseTimer=.28;beep('throw')}
function updateTank(dt){if(!tank.flying)return;tank.vy+=GRAVITY*F.gravityMultiplier*dt;tank.x+=tank.vx*dt;tank.y+=tank.vy*dt;tank.angle+=tank.angular*dt;if(!tank.hitCarl&&Math.hypot(tank.x-carl.x,tank.y-(carl.y-90))<94+F.collisionBonus){tank.hitCarl=true;if(carl.exposed){damageCarl(tank.returned?2:1,tank.returned?'RETURN TO SENDER':'DIRECT HIT');tank.vx*=F.impactX;tank.vy*=F.impactY}else{dodges++;toast('TOO SLOW! CARL WAS ALREADY GONE.',600);tank.vx*=.72;tank.vy*=.8}}if(tank.y>=GROUND-22){tank.y=GROUND-22;if(Math.abs(tank.vy)>150&&!tank.bounced){tank.vy*=F.bounceY;tank.vx*=F.bounceX;tank.bounced=true;impact(tank.x,tank.y+8)}else{tank.vy=0;tank.vx*=Math.pow(.07,dt)}}if(tank.x<-450||tank.x>2100||(tank.y>=GROUND-23&&Math.abs(tank.vx)<13)){tank.resetTimer+=dt;if(tank.resetTimer>.55)resetTank(true)}else tank.resetTimer=0}
function finishWin(){if(win)return;win=true;running=false;incoming.active=false;aim=null;toast('COLONEL CARL FINALLY STOPPED MOVING!',1600);beep('win');const stars=1+(catches>=3?1:0)+(health===5?1:0);starsEl.textContent='★'.repeat(stars)+'☆'.repeat(3-stars);rScore.textContent=score.toLocaleString();rHits.textContent=hits;rCatches.textContent=catches;rDodges.textContent=dodges;rDefense.textContent=health===5?'UNTOUCHED':`${health}/5 HEARTS`;setTimeout(()=>winScreen.classList.add('visible'),900)}
function reset(){running=true;over=win=false;score=0;health=5;hp=MAX_HP;phase=1;elapsed=0;steroids=3;steroidTimer=0;aim=null;cameraX=0;shake=0;hits=catches=misses=dodges=0;attackClock=1.4;catchHolding=false;catchPointer=null;incoming.active=false;particles.length=floaters.length=afterimages.length=0;Object.assign(carl,{x:1080,y:GROUND-43,side:1,state:'idle',timer:1.3,fromX:1080,toX:1080,progress:0,exposed:false,hitFlash:0,fake:false});Object.assign(hero,{armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0});resetTank(true);steroidButton.disabled=false;steroidCountEl.textContent='3 demo doses';hud();toast('BOSS 5: COLONEL CARL THE CHEETAH',1400)}
function update(dt){if(!running){cameraX=updateCamera(cameraX,tank,aim,running,dt);updateJohnny(hero,tank,aim,running,dt);return}elapsed+=dt;if(steroidTimer>0)steroidTimer=Math.max(0,steroidTimer-dt);updateCarl(dt);updateIncoming(dt);updateTank(dt);for(const a of afterimages)a.life-=dt;for(const p of particles){p.life-=dt;p.vy+=420*dt;p.x+=p.vx*dt;p.y+=p.vy*dt}for(const f of floaters){f.life-=dt;f.y-=45*dt}for(let i=afterimages.length-1;i>=0;i--)if(afterimages[i].life<=0)afterimages.splice(i,1);for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1);shake*=Math.pow(.002,dt);cameraX=updateCamera(cameraX,tank,aim,running,dt);if(caughtTank&&tank.ready&&!aim)hero.catchPose=Math.max(hero.catchPose,.08);updateJohnny(hero,tank,aim,running,dt);hud()}
function drawBg(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#4e6375');sky.addColorStop(.66,'#c98559');sky.addColorStop(1,'#d49a5f');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#8a5135';for(let x=-100;x<W+200;x+=250){ctx.beginPath();ctx.moveTo(x,GROUND);ctx.lineTo(x+70,GROUND-110);ctx.lineTo(x+155,GROUND-75);ctx.lineTo(x+250,GROUND);ctx.closePath();ctx.fill()}ctx.fillStyle='#b47444';ctx.fillRect(0,GROUND-25,W,25);ctx.fillStyle='#503052';for(let x=1040;x<1500;x+=130){ctx.beginPath();ctx.moveTo(x,GROUND-25);ctx.lineTo(x+18,GROUND-75);ctx.lineTo(x+34,GROUND-25);ctx.fill()}}
function drawCarlAt(x,y,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.scale(1.35,1.35);const fur=carl.hitFlash>0?'#fff0c0':'#d9aa55',ink='#2a2117',uniform='#6c6540';ctx.strokeStyle=ink;ctx.lineWidth=11;ctx.beginPath();ctx.moveTo(35,-55);ctx.quadraticCurveTo(80,-68,88,-28);ctx.stroke();ctx.fillStyle=uniform;ctx.beginPath();ctx.ellipse(0,-78,45,40,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=fur;ctx.beginPath();ctx.ellipse(0,-145,35,39,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=ink;for(const p of[[-21,-165],[-8,-151],[15,-164],[24,-145],[-26,-132],[9,-126]]){ctx.beginPath();ctx.arc(p[0],p[1],4,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#f4e4c4';ctx.beginPath();ctx.ellipse(0,-134,20,16,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=ink;ctx.beginPath();ctx.moveTo(-5,-138);ctx.lineTo(5,-138);ctx.lineTo(0,-131);ctx.fill();ctx.fillStyle='#1d1f1b';ctx.fillRect(-39,-116,78,10);ctx.fillStyle='#d5b24f';ctx.font='900 9px system-ui';ctx.textAlign='center';ctx.fillText('COL',0,-89);ctx.strokeStyle=ink;ctx.lineWidth=15;ctx.beginPath();ctx.moveTo(-24,-62);ctx.lineTo(-45,-5);ctx.moveTo(24,-62);ctx.lineTo(45,-5);ctx.stroke();ctx.restore()}
function render(){ctx.clearRect(0,0,W,H);ctx.save();if(shake>.4)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawBg();ctx.save();ctx.translate(-cameraX,0);for(const a of afterimages)drawCarlAt(a.x,a.y,.18*(a.life/a.max));if(carl.state==='dash')drawCarlAt(carl.x,carl.y,.7);ctx.save();ctx.translate(24,3);ctx.translate(142,582);ctx.scale(.5,.5);ctx.translate(-142,-582);S.drawJohnny(ctx,hero,steroidTimer,elapsed);ctx.restore();if(carl.state!=='dash')drawCarlAt(carl.x,carl.y,1);if(incoming.active)T.drawTank(ctx,{x:incoming.x,y:incoming.y,angle:incoming.angle});if(!tank.flying&&aim){const h=held();T.drawTank(ctx,{...tank,x:h.x,y:h.y,angle:-.08})}else T.drawTank(ctx,tank);if(aim&&!tank.flying){ctx.strokeStyle='#ffcf33';ctx.lineWidth=4;ctx.setLineDash([10,8]);ctx.beginPath();ctx.moveTo(tank.x,tank.y);ctx.lineTo(aim.x,aim.y);ctx.stroke();ctx.setLineDash([])}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=Math.max(0,f.life);ctx.fillStyle='#fff2a3';ctx.font='900 24px Impact,system-ui';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;ctx.textAlign='left';ctx.restore();ctx.restore()}
function frame(now){const dt=Math.min((now-last)/1000,.033);last=now;update(dt);render();requestAnimationFrame(frame)}
canvas.addEventListener('pointerdown',e=>{if(!running)return;const p=pointerToWorld(canvas,e,cameraX);if(incomingInWindow()&&Math.hypot(p.x-incoming.x,p.y-incoming.y)<135){catchHolding=true;catchPointer=e.pointerId;incoming.hold=0;canvas.setPointerCapture?.(e.pointerId);return}if(tank.flying||!tank.ready)return;if(Math.hypot(p.x-tank.x,p.y-tank.y)<135){aim=p;canvas.setPointerCapture?.(e.pointerId)}});canvas.addEventListener('pointermove',e=>{if(catchHolding)return;if(!aim||tank.flying)return;const p=pointerToWorld(canvas,e,cameraX),dx=p.x-tank.x,dy=p.y-tank.y,l=Math.hypot(dx,dy);aim=l>MAX_PULL?{x:tank.x+dx/l*MAX_PULL,y:tank.y+dy/l*MAX_PULL}:p});canvas.addEventListener('pointerup',e=>{if(catchHolding&&e.pointerId===catchPointer){catchHolding=false;catchPointer=null;incoming.hold=0;return}throwTank()});canvas.addEventListener('pointercancel',()=>{catchHolding=false;catchPointer=null;aim=null});
steroidButton.addEventListener('click',()=>{if(!running||steroids<=0)return;steroids--;steroidTimer=12;steroidCountEl.textContent=steroids===1?'1 demo dose':`${steroids} demo doses`;steroidButton.disabled=steroids<=0;toast('UNREGULATED STRENGTH!');beep('power')});muteButton.addEventListener('click',()=>{muted=!muted;muteButton.textContent=muted?'🔇':'🔊'});$('start').addEventListener('click',()=>{titleScreen.classList.remove('visible');reset()});$('restart').addEventListener('click',()=>{overScreen.classList.remove('visible');reset()});$('replay').addEventListener('click',()=>{winScreen.classList.remove('visible');reset()});hud();render();requestAnimationFrame(frame);
})();