(() => {
  'use strict';
  const S=window.JMShared;
  if(!S) throw new Error('campaign-shared.js must load before city5.js');
  const {W,H,GROUND,GRAVITY,TANK_HOME,MAX_PULL,clamp,pseudoRandom,pointerToWorld,drawTank,drawJohnny,drawAim,updateCamera,updateJohnny}=S;
  const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
  const scoreEl=document.getElementById('score'),healthEl=document.getElementById('health'),comboEl=document.getElementById('combo'),waveEl=document.getElementById('wave'),remainingEl=document.getElementById('remaining'),pulseEl=document.getElementById('pulses');
  const steroidButton=document.getElementById('steroids'),steroidCountEl=document.getElementById('steroid-count'),muteButton=document.getElementById('mute');
  const titleScreen=document.getElementById('title-screen'),gameOverScreen=document.getElementById('game-over'),missionCompleteScreen=document.getElementById('mission-complete'),finalScoreEl=document.getElementById('final-score'),toastEl=document.getElementById('toast');
  const resultStarsEl=document.getElementById('result-stars'),resultScoreEl=document.getElementById('result-score'),resultCatsEl=document.getElementById('result-cats'),resultBrainsEl=document.getElementById('result-brains'),resultPulsesEl=document.getElementById('result-pulses'),resultComboEl=document.getElementById('result-combo'),resultDefenseEl=document.getElementById('result-defense');

  const DEFENSE_X=86;
  const LEVEL={waves:[
    {ground:4,bats:3,brains:1,gap:.82,batSpeed:74,chonker:.06},
    {ground:5,bats:4,brains:2,gap:.72,batSpeed:84,chonker:.12},
    {ground:6,bats:5,brains:2,gap:.62,batSpeed:94,chonker:.18}
  ]};
  const LEDGES=[{x:610,y:405,w:220},{x:1180,y:330,w:245},{x:1700,y:385,w:230}];

  let lastTime=performance.now(),running=false,gameOver=false,missionComplete=false,score=0,health=5,combo=1,bestCombo=1,comboTimer=0,elapsed=0,steroidsLeft=3,steroidTimer=0,muted=false,audioCtx=null,aim=null,shake=0,cameraX=0,toastTimer=null;
  let currentWave=-1,queue=[],spawned=0,resolved=0,spawnTimer=0,intermission=1.1,clearAnnounced=false,finishTimer=0;
  let flattened=0,brainKills=0,pulseDeflections=0,breaches=0;
  const cats=[],particles=[],floaters=[];
  const tank={x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,resetTimer:0,bounced:false,hitIds:new Set(),hitLedges:new Set()};
  const johnny={armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0};

  function showToast(text,duration=850){toastEl.textContent=text;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),duration);}
  function beep(type='impact'){if(muted)return;try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),n=audioCtx.currentTime,s={throw:[90,52,.12,'sawtooth'],impact:[72,38,.09,'square'],cat:[430,240,.08,'triangle'],bat:[520,860,.09,'triangle'],brain:[210,520,.22,'sawtooth'],pulse:[125,880,.35,'sine'],hurt:[120,70,.22,'square'],wave:[260,410,.18,'square'],win:[330,660,.42,'triangle'],power:[160,420,.25,'sawtooth']}[type]||[120,80,.1,'sine'];o.type=s[3];o.frequency.setValueAtTime(s[0],n);o.frequency.exponentialRampToValueAtTime(s[1],n+s[2]);g.gain.setValueAtTime(.055,n);g.gain.exponentialRampToValueAtTime(.001,n+s[2]);o.connect(g).connect(audioCtx.destination);o.start(n);o.stop(n+s[2]);}catch(_){} }
  function updateHud(){scoreEl.textContent=String(score).padStart(6,'0');healthEl.textContent=Array.from({length:5},(_,i)=>i<health?'♥':'♡').join(' ');comboEl.textContent=`x${combo}`;pulseEl.textContent=String(pulseDeflections);if(currentWave<0){waveEl.textContent='1/3';remainingEl.textContent='INCOMING';return;}const s=LEVEL.waves[currentWave],total=s.ground+s.bats+s.brains;waveEl.textContent=`${currentWave+1}/3`;remainingEl.textContent=missionComplete?'SECURED':String(Math.max(0,total-resolved));}
  function resetTank(){Object.assign(tank,{x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,resetTimer:0,bounced:false});tank.hitIds.clear();tank.hitLedges.clear();aim=null;johnny.releaseTimer=0;}
  function resetGame(){running=true;gameOver=false;missionComplete=false;score=0;health=5;combo=1;bestCombo=1;comboTimer=0;elapsed=0;steroidsLeft=3;steroidTimer=0;aim=null;shake=0;cameraX=0;currentWave=-1;queue=[];spawned=0;resolved=0;spawnTimer=0;intermission=1.1;clearAnnounced=false;finishTimer=0;flattened=0;brainKills=0;pulseDeflections=0;breaches=0;cats.length=0;particles.length=0;floaters.length=0;Object.assign(johnny,{armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0});resetTank();steroidButton.disabled=false;steroidCountEl.textContent='3 demo doses';updateHud();showToast('CITY 5: DOWNTOWN DISASTER',1200);}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function startWave(){currentWave++;const s=LEVEL.waves[currentWave];queue=shuffle([...Array(s.ground).fill('ground'),...Array(s.bats).fill('bat'),...Array(s.brains).fill('brain')]);spawned=0;resolved=0;spawnTimer=.2;clearAnnounced=false;showToast(`WAVE ${currentWave+1} · EVERYTHING AT ONCE`,950);beep('wave');updateHud();}
  function spawnCat(kind){const s=LEVEL.waves[currentWave],isBat=kind==='bat',isBrain=kind==='brain',chonker=kind==='ground'&&Math.random()<s.chonker,scale=chonker?1.5:isBrain?1.05:isBat?.82+Math.random()*.16:.9+Math.random()*.2,hp=chonker?2:isBrain?2:1;cats.push({id:`${kind}-${performance.now()}-${Math.random()}`,kind,x:1180+Math.random()*260,y:isBat?250:isBrain?260:GROUND-29*scale,baseY:isBat?220+Math.random()*170:isBrain?250+Math.random()*90:GROUND-29*scale,scale,hp,maxHp:hp,chonker,speed:isBat?s.batSpeed+Math.random()*14:isBrain?22+Math.random()*7:(chonker?38:58+Math.random()*19),phase:Math.random()*6.2,phaseSpeed:1.45+Math.random()*.5,amp:isBat?54+Math.random()*42:0,pulseTimer:isBrain?1.7+Math.random()*1.0:99,bob:Math.random()*6.2,dead:false,resolved:false});spawned++;updateHud();}
  function resolveCat(c,defeated){if(c.resolved)return;c.resolved=true;c.dead=true;resolved++;if(defeated)flattened++;updateHud();}
  function addImpact(x,y,strong=false){for(let i=0;i<(strong?22:11);i++){const a=Math.random()*Math.PI*2,s=70+Math.random()*(strong?300:150);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-80,life:.35+Math.random()*.5,max:.85,size:3+Math.random()*9});}shake=Math.max(shake,strong?15:7);}
  function killCat(c,impact){const kind=c.kind;resolveCat(c,true);if(kind==='brain')brainKills++;const base=c.chonker?350:kind==='brain'?420:kind==='bat'?260:130,pts=(base+Math.floor(Math.min(impact/8,120)))*combo;score+=pts;combo=Math.min(12,combo+1);bestCombo=Math.max(bestCombo,combo);comboTimer=2.1;floaters.push({x:c.x,y:c.y-24,text:kind==='brain'?`BRAIN +${pts}`:`+${pts}`,life:.9});addImpact(c.x,c.y,c.chonker||kind!=='ground'||impact>650);beep(kind==='brain'?'brain':kind==='bat'?'bat':'cat');if(kind==='brain')showToast('MIND OVER SPLATTER!',700);updateHud();}
  function emitPulse(c){if(c.dead)return;beep('pulse');particles.push({ring:true,x:c.x,y:c.y,life:.55,max:.55,size:10});if(tank.flying&&Math.hypot(tank.x-c.x,tank.y-c.y)<700){const dir=Math.sin(c.phase)>=0?1:-1;tank.vy+=dir*135;tank.vx*=.965;pulseDeflections++;floaters.push({x:tank.x,y:tank.y-28,text:'PSYCHIC SHOVE!',life:.8});showToast('BRAINCAT BENT THE SHOT!',650);shake=Math.max(shake,7);updateHud();}}
  function updateCat(c,dt){if(c.dead)return;c.bob+=dt*7;c.phase+=c.phaseSpeed*dt;if(c.kind==='bat'){c.x-=c.speed*dt;c.y=clamp(c.baseY+Math.sin(c.phase*2.2)*c.amp+Math.sin(c.phase*.7)*18,165,GROUND-100);}else if(c.kind==='brain'){c.x-=c.speed*dt;c.y=c.baseY+Math.sin(c.phase)*12;c.pulseTimer-=dt;if(c.pulseTimer<=0){emitPulse(c);c.pulseTimer=2.5+Math.random()*.65;}}else{c.x-=c.speed*dt;c.y=GROUND-29*c.scale;}if(c.x<DEFENSE_X){breaches++;health--;combo=1;comboTimer=0;resolveCat(c,false);showToast(c.kind==='brain'?'BRAINCAT BREACH!':'DEFENSE BREACH!');beep('hurt');shake=12;updateHud();if(health<=0)endGame();}}
  function updateMission(dt){if(gameOver||missionComplete)return;if(currentWave<0){intermission-=dt;if(intermission<=0)startWave();return;}const s=LEVEL.waves[currentWave],total=s.ground+s.bats+s.brains;if(spawned<total){spawnTimer-=dt;if(spawnTimer<=0){spawnCat(queue[spawned]);spawnTimer=s.gap;}return;}if(resolved<total||cats.some(c=>!c.dead))return;if(currentWave<2){if(!clearAnnounced){clearAnnounced=true;intermission=1.45;showToast(`WAVE ${currentWave+1} CLEAR`,800);return;}intermission-=dt;if(intermission<=0)startWave();return;}finishTimer+=dt;if(finishTimer>.75)completeMission();}
  function completeMission(){if(missionComplete)return;missionComplete=true;running=false;aim=null;showToast('DOWNTOWN SECURED',1300);beep('win');const stars=1+(breaches===0?1:0)+(pulseDeflections<=2?1:0);resultStarsEl.textContent='★'.repeat(stars)+'☆'.repeat(3-stars);resultScoreEl.textContent=score.toLocaleString();resultCatsEl.textContent=String(flattened);resultBrainsEl.textContent=String(brainKills);resultPulsesEl.textContent=String(pulseDeflections);resultComboEl.textContent=`x${bestCombo}`;resultDefenseEl.textContent=breaches===0?'UNTOUCHED':`${health}/5 HEARTS`;setTimeout(()=>missionCompleteScreen.classList.add('visible'),850);}
  function endGame(){running=false;gameOver=true;aim=null;finalScoreEl.textContent=`Score: ${score.toLocaleString()} · Psychic shoves: ${pulseDeflections}`;gameOverScreen.classList.add('visible');}

  function held(){return !aim||tank.flying?{x:tank.x,y:tank.y}:{x:aim.x,y:Math.min(aim.y,GROUND-40)};}
  function throwTank(){if(!aim||tank.flying||!running)return;const dx=tank.x-aim.x,dy=tank.y-aim.y,p=Math.hypot(dx,dy);if(p<18){aim=null;return;}const sc=Math.min(p,MAX_PULL)/p,b=steroidTimer>0?1.42:1,h=held();Object.assign(tank,{x:h.x,y:h.y,vx:dx*sc*4.05*b,vy:dy*sc*4.05*b,angular:Math.min(9,2+p/55),flying:true,bounced:false});tank.hitIds.clear();tank.hitLedges.clear();aim=null;johnny.releaseTimer=.28;beep('throw');if(navigator.vibrate)navigator.vibrate(20);}
  function updateTank(dt){if(!tank.flying)return;const prevY=tank.y;tank.vy+=GRAVITY*dt;tank.x+=tank.vx*dt;tank.y+=tank.vy*dt;tank.angle+=tank.angular*dt;const impact=Math.hypot(tank.vx,tank.vy);for(let i=0;i<LEDGES.length;i++){const l=LEDGES[i];if(tank.hitLedges.has(i))continue;if(tank.vy>0&&prevY<l.y-18&&tank.y>=l.y-18&&tank.x>l.x-35&&tank.x<l.x+l.w+35){tank.y=l.y-18;tank.vy*=-.46;tank.vx*=.9;tank.angular*=.78;tank.hitLedges.add(i);floaters.push({x:tank.x,y:tank.y-20,text:'BANK!',life:.65});beep('impact');}}for(const c of cats){if(c.dead||tank.hitIds.has(c.id))continue;const r=c.kind==='bat'?48*c.scale:c.kind==='brain'?55:37+25*c.scale;if(Math.hypot(tank.x-c.x,tank.y-c.y)<r){tank.hitIds.add(c.id);const dmg=(steroidTimer>0?2:1)+(impact>760?1:0);c.hp-=dmg;tank.vx*=.86;tank.vy*=.9;addImpact(c.x,c.y,dmg>1);if(c.hp<=0)killCat(c,impact);else{floaters.push({x:c.x,y:c.y-35,text:'BONK!',life:.7});beep('impact');}}}if(tank.y>=GROUND-22){tank.y=GROUND-22;if(Math.abs(tank.vy)>160&&!tank.bounced){tank.vy*=-.30;tank.vx*=.74;tank.angular*=.65;tank.bounced=true;addImpact(tank.x,tank.y+15,true);beep('impact');}else{tank.vy=0;tank.vx*=Math.pow(.055,dt);tank.angular*=Math.pow(.03,dt);}}if(tank.x<-260||(tank.y>=GROUND-23&&Math.abs(tank.vx)<14)){tank.resetTimer+=dt;if(tank.resetTimer>.65)resetTank();}else tank.resetTimer=0;}
  function update(dt){if(!running){cameraX=updateCamera(cameraX,tank,aim,running,dt);updateJohnny(johnny,tank,aim,running,dt);return;}elapsed+=dt;if(steroidTimer>0)steroidTimer=Math.max(0,steroidTimer-dt);if(comboTimer>0){comboTimer-=dt;if(comboTimer<=0&&combo!==1){combo=1;updateHud();}}updateMission(dt);for(const c of cats)updateCat(c,dt);updateTank(dt);for(const p of particles){p.life-=dt;if(!p.ring){p.vy+=420*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;}}for(const f of floaters){f.life-=dt;f.y-=48*dt;}for(let i=cats.length-1;i>=0;i--)if(cats[i].dead)cats.splice(i,1);for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1);shake*=Math.pow(.002,dt);cameraX=updateCamera(cameraX,tank,aim,running,dt);updateJohnny(johnny,tank,aim,running,dt);}

  function drawBackground(){const sky=ctx.createLinearGradient(0,0,0,GROUND);sky.addColorStop(0,'#13172b');sky.addColorStop(.6,'#34384c');sky.addColorStop(1,'#775355');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);for(let layer=0;layer<3;layer++){const factor=.07+layer*.06,spacing=150+layer*35,off=-(((cameraX*factor%spacing)+spacing)%spacing);for(let i=-2;i<10;i++){const x=i*spacing+off,h=180+layer*55+pseudoRandom(i,layer)*210;ctx.fillStyle=['#1d2332','#252a39','#303443'][layer];ctx.fillRect(x,GROUND-h,spacing-25,h);}}ctx.fillStyle='#403b3c';ctx.fillRect(0,GROUND,W,H-GROUND);ctx.fillStyle='#5c5556';ctx.fillRect(0,GROUND,W,7);}
  function drawWorld(){for(const l of LEDGES){ctx.fillStyle='#626a73';ctx.fillRect(l.x,l.y,l.w,10);ctx.strokeStyle='#7d858f';ctx.lineWidth=4;for(let x=l.x+10;x<l.x+l.w;x+=36){ctx.beginPath();ctx.moveTo(x,l.y);ctx.lineTo(x,l.y+42);ctx.stroke();}}for(let x=420;x<2000;x+=360){const h=280+pseudoRandom(x,5)*180;ctx.fillStyle='#2b303a';ctx.fillRect(x,GROUND-h,260,h);ctx.fillStyle='rgba(245,211,118,.10)';for(let wx=x+30;wx<x+230;wx+=55)for(let wy=GROUND-h+45;wy<GROUND-50;wy+=65)if(pseudoRandom(wx+wy,8)>.46)ctx.fillRect(wx,wy,18,25);}}
  function drawCat(c){ctx.save();ctx.translate(c.x,c.y+Math.sin(c.bob)*2);ctx.scale(c.scale,c.scale);if(c.kind==='brain'){ctx.fillStyle='#4e3b61';ctx.beginPath();ctx.ellipse(0,5,25,18,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(-15,-15,27,0,Math.PI*2);ctx.fill();ctx.fillStyle='#b86cff';ctx.beginPath();ctx.arc(-17,-19,15,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(196,110,255,.75)';ctx.lineWidth=4;if(c.pulseTimer<.6){const r=36+(0.6-c.pulseTimer)*70;ctx.beginPath();ctx.arc(-15,-15,r,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='#80ff69';ctx.beginPath();ctx.arc(-24,-18,4,0,Math.PI*2);ctx.arc(-10,-18,4,0,Math.PI*2);ctx.fill();}else if(c.kind==='bat'){ctx.fillStyle='#49384f';ctx.beginPath();ctx.ellipse(0,0,26,18,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-15,-3);ctx.lineTo(-52,-28);ctx.lineTo(-42,10);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(15,-3);ctx.lineTo(52,-28);ctx.lineTo(42,10);ctx.closePath();ctx.fill();ctx.fillStyle='#77ff62';ctx.beginPath();ctx.arc(-7,-7,4,0,Math.PI*2);ctx.arc(7,-7,4,0,Math.PI*2);ctx.fill();}else{ctx.fillStyle=c.chonker?'#3e3344':'#554358';ctx.beginPath();ctx.ellipse(0,0,31,22,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(-22,-18,20,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-38,-31);ctx.lineTo(-34,-50);ctx.lineTo(-22,-35);ctx.fill();ctx.beginPath();ctx.moveTo(-12,-35);ctx.lineTo(-4,-49);ctx.lineTo(0,-29);ctx.fill();ctx.fillStyle=c.hp<c.maxHp?'#ffe34e':'#77ff62';ctx.beginPath();ctx.arc(-29,-20,4,0,Math.PI*2);ctx.arc(-17,-20,4,0,Math.PI*2);ctx.fill();}ctx.restore();}
  function render(){ctx.clearRect(0,0,W,H);ctx.save();if(shake>.4)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawBackground();ctx.save();ctx.translate(-cameraX,0);drawWorld();drawJohnny(ctx,johnny,steroidTimer,elapsed);drawAim(ctx,tank,aim,steroidTimer);if(aim&&!tank.flying&&running){const h=held();drawTank(ctx,{...tank,x:h.x,y:h.y,angle:-.08});}else drawTank(ctx,tank);for(const c of cats)drawCat(c);for(const p of particles){if(p.ring){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.strokeStyle='#c06cff';ctx.lineWidth=7;ctx.beginPath();ctx.arc(p.x,p.y,30+(1-p.life/p.max)*520,0,Math.PI*2);ctx.stroke();}else{ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle='#ffd85a';ctx.fillRect(p.x-p.size/2,p.y-p.size/2,p.size,p.size);}}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=Math.max(0,f.life/.9);ctx.fillStyle='#fff4a5';ctx.font='900 23px Impact, system-ui, sans-serif';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y);}ctx.globalAlpha=1;ctx.textAlign='left';ctx.restore();ctx.restore();}
  function frame(now){const dt=Math.min((now-lastTime)/1000,.033);lastTime=now;update(dt);render();requestAnimationFrame(frame);}

  canvas.addEventListener('pointerdown',e=>{if(!running||tank.flying||gameOver||missionComplete)return;const p=pointerToWorld(canvas,e,cameraX);if(Math.hypot(p.x-tank.x,p.y-tank.y)<105){aim=p;canvas.setPointerCapture?.(e.pointerId);}});
  canvas.addEventListener('pointermove',e=>{if(!aim||tank.flying)return;const p=pointerToWorld(canvas,e,cameraX),dx=p.x-tank.x,dy=p.y-tank.y,l=Math.hypot(dx,dy);aim=l>MAX_PULL?{x:tank.x+dx/l*MAX_PULL,y:tank.y+dy/l*MAX_PULL}:p;});canvas.addEventListener('pointerup',()=>throwTank());canvas.addEventListener('pointercancel',()=>{aim=null;});
  steroidButton.addEventListener('click',()=>{if(!running||steroidsLeft<=0)return;steroidsLeft--;steroidTimer=12;steroidCountEl.textContent=steroidsLeft===1?'1 demo dose':`${steroidsLeft} demo doses`;steroidButton.disabled=steroidsLeft<=0;showToast('UNREGULATED STRENGTH!');beep('power');});
  muteButton.addEventListener('click',()=>{muted=!muted;muteButton.textContent=muted?'🔇':'🔊';});document.getElementById('start').addEventListener('click',()=>{titleScreen.classList.remove('visible');resetGame();beep('power');});document.getElementById('restart').addEventListener('click',()=>{gameOverScreen.classList.remove('visible');resetGame();});document.getElementById('replay').addEventListener('click',()=>{missionCompleteScreen.classList.remove('visible');resetGame();});
  updateHud();render();requestAnimationFrame(frame);
})();