(() => {
'use strict';
const S=window.JMShared,T=window.JMTankArt,F=window.JMWorld4Fighter,E=window.JMEnemyArt;
if(!S||!T||!F||!E) throw new Error('Infested Zone requires shared, tank, fighter, and enemy art modules');
const {W,H,GROUND,GRAVITY,TANK_HOME,MAX_PULL,clamp,pointerToWorld,updateCamera,updateJohnny}=S;
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),level=Number(document.getElementById('game-shell').dataset.level||1);
const CFG={
1:{title:'PURPLE HAZE',tag:'STOP THE MUTATION',mechanics:{spores:true},waves:[['alienling','sporeling','alienling','sporeling'],['sporeling','alienling','leaper','alienling','sporeling'],['sporeling','alienling','chonker','sporeling','leaper','alienling']]},
2:{title:'THE HIVE MIND',tag:'BREAK THE LINK',mechanics:{controllers:true},waves:[['controller','alienling','alienling','sporeling'],['controller','leaper','alienling','controller','sporeling'],['controller','armored','alienling','controller','chonker','leaper']]},
3:{title:'LIVING GROUND',tag:'USE THE TENDRILS',mechanics:{tendrils:true},waves:[['alienling','leaper','sporeling','alienling'],['armored','alienling','leaper','chonker','sporeling'],['leaper','armored','chonker','alienling','leaper','sporeling']]},
4:{title:'MUTATION STATION',tag:'BREAK THE PODS',mechanics:{pods:true,controllers:true},waves:[['alienling','alienling','sporeling','alienling'],['alienling','controller','alienling','leaper','alienling'],['alienling','armored','alienling','chonker','controller','alienling']]},
5:{title:"NO MAN'S LAND",tag:'SURVIVE THE INFESTATION',mechanics:{spores:true,controllers:true,tendrils:true,pods:true},waves:[['controller','alienling','sporeling','leaper'],['armored','controller','alienling','chonker','sporeling'],['controller','armored','chonker','leaper','sporeling','alienling','controller']]}
}[level];

const $=id=>document.getElementById(id);
const scoreEl=$('score'),healthEl=$('health'),waveEl=$('wave'),remainEl=$('remaining'),mutationEl=$('mutations'),controlEl=$('control'),steroidButton=$('steroids'),steroidCountEl=$('steroid-count'),muteButton=$('mute'),titleScreen=$('title-screen'),overScreen=$('game-over'),winScreen=$('mission-complete'),finalScoreEl=$('final-score'),toastEl=$('toast'),rStars=$('result-stars'),rScore=$('result-score'),rCats=$('result-cats'),rMutations=$('result-mutations'),rSpecial=$('result-special'),rDefense=$('result-defense');
let last=performance.now(),running=false,over=false,done=false,score=0,health=5,wave=-1,spawned=0,resolved=0,queue=[],spawnTimer=0,between=.35,finishTimer=0,elapsed=0,muted=false,audio=null,steroids=3,steroidTimer=0,cameraX=0,aim=null,shake=0,toastTimer=null,flattened=0,mutations=0,specialKills=0,sporeClock=1.5;
const actors=[],spores=[],tendrils=[],pods=[],particles=[],floaters=[];
const hero={armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0};
const tank={x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,resetTimer:0,bounced:false,hitIds:new Set(),tendrilKey:''};
const terrainY=x=>GROUND-10+Math.sin(x*.0048+level)*7+Math.sin(x*.013)*3;
const toast=(t,d=850)=>{toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),d)};
function beep(type='hit'){if(muted)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime,m={throw:[96,52,.1],hit:[82,44,.09],mutate:[190,70,.18],control:[420,170,.15],tendril:[110,260,.18],hurt:[120,70,.2],win:[330,880,.45],power:[160,420,.25]}[type]||[120,80,.1];o.type=type==='mutate'?'sawtooth':'square';o.frequency.setValueAtTime(m[0],n);o.frequency.exponentialRampToValueAtTime(m[1],n+m[2]);g.gain.setValueAtTime(.05,n);g.gain.exponentialRampToValueAtTime(.001,n+m[2]);o.connect(g).connect(audio.destination);o.start(n);o.stop(n+m[2])}catch{}}
function impact(x,y,strong=false,c='#d487ec'){for(let i=0;i<(strong?25:12);i++){const a=Math.random()*Math.PI*2,s=60+Math.random()*(strong?290:150);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-80,life:.35+Math.random()*.4,max:.75,size:2+Math.random()*7,c})}shake=Math.max(shake,strong?16:7)}
function hud(){scoreEl.textContent=String(score).padStart(6,'0');healthEl.textContent=Array.from({length:5},(_,i)=>i<health?'♥':'♡').join(' ');waveEl.textContent=`${Math.max(1,wave+1)}/3`;remainEl.textContent=wave<0?'INCOMING':String(Math.max(0,queue.length-resolved));mutationEl.textContent=String(mutations);controlEl.textContent=actors.some(a=>!a.dead&&a.kind==='controller'&&a.linkId)?'LINKED':'CLEAR';}
function resetTank(){Object.assign(tank,{x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,resetTimer:0,bounced:false,tendrilKey:''});tank.hitIds.clear();aim=null}
function mutateActor(a,source='spores'){if(!a||a.dead||a.mutated||!['alienling','sporeling'].includes(a.kind))return false;const r=Math.random();a.kind=r<.38?'leaper':r<.72?'armored':'chonker';a.scale=a.kind==='chonker'?1.4:a.kind==='armored'?1.08:.96;a.speed=a.kind==='chonker'?47:a.kind==='armored'?52:66;a.armor=a.kind==='armored'?1:0;a.mutated=true;mutations++;score+=100;floaters.push({x:a.x,y:a.y-90,text:source==='pod'?'POD MUTATION!':'MUTATION!',life:.85});impact(a.x,a.y-25,true,'#c667ef');beep('mutate');hud();return true}
function actor(kind,index){const x=960+index*138+Math.random()*80;return{id:`${wave}-${index}-${Math.random()}`,kind,x,y:terrainY(x)-28,vy:0,airborne:false,speed:kind==='controller'?42:kind==='leaper'?66:kind==='armored'?52:kind==='chonker'?47:kind==='sporeling'?62:60,scale:kind==='chonker'?1.4:kind==='armored'?1.08:kind==='sporeling'?.82:kind==='alienling'?.78:.95,dead:false,phase:Math.random()*6.2,boost:1,linkId:null,linkPulse:0,jumpTimer:kind==='leaper'?.8+Math.random():0,mutated:false,armor:kind==='armored'?1:0,tendrilTag:0};}
function setupEnvironment(){spores.length=tendrils.length=pods.length=0;if(CFG.mechanics.tendrils){for(const x of [720,1120,1540,1940])tendrils.push({x,timer:.9+(x%300)/300*1.2,active:0,cycle:0})}if(CFG.mechanics.pods){for(const x of level===5?[980,1510,2050]:[1020,1600])pods.push({x,y:terrainY(x)-20,hp:2,dead:false,timer:2.8+Math.random()*1.5,pulse:Math.random()*6.2})}}
function startWave(){wave++;queue=CFG.waves[wave].slice();spawned=resolved=0;spawnTimer=.25;between=0;finishTimer=0;toast(`WAVE ${wave+1}: ${CFG.tag}`,1100);hud()}
function kill(a,why='vehicle'){if(a.dead)return;a.dead=true;resolved++;flattened++;if(a.kind==='controller')specialKills++;score+=a.kind==='controller'?600:a.kind==='chonker'?500:350;impact(a.x,a.y-12,true,a.kind==='controller'?'#ffdf72':'#cf76ec');floaters.push({x:a.x,y:a.y-75,text:a.kind==='controller'?'LINK BROKEN!':why==='tendril'?'TENDRIL ASSIST!':'WHAM!',life:.8});if(why==='tendril')score+=250;beep('hit');for(const b of actors)if(b.linkSource===a.id){b.linkSource=null;b.boost=1}hud()}
function hurt(t){if(over||done)return;health--;shake=20;impact(170,GROUND-85,true,'#ffaf78');toast(t,850);beep('hurt');hud();if(health<=0){running=false;over=true;finalScoreEl.textContent=`Score: ${score.toLocaleString()} · Mutations: ${mutations}`;overScreen.classList.add('visible')}}
function spawn(){actors.push(actor(queue[spawned],spawned));spawned++;spawnTimer=.58+Math.random()*.22}
function spawnSpore(){const x=820+Math.random()*1180,y=terrainY(x)-70-Math.random()*80;spores.push({x,y,r:34,life:4.5,max:4.5,vx:-18-Math.random()*18,pulse:Math.random()*6.2});}
function updateSpores(dt){if(!CFG.mechanics.spores)return;sporeClock-=dt;if(sporeClock<=0){spawnSpore();sporeClock=1.65+Math.random()*1.2}for(const s of spores){s.life-=dt;s.x+=s.vx*dt;s.y+=Math.sin(elapsed*2+s.pulse)*5*dt;s.r=Math.min(62,s.r+7*dt);for(const a of actors){if(a.dead||a.mutated)continue;if(Math.hypot(a.x-s.x,a.y-s.y)<s.r*.9)mutateActor(a,'spores')}}for(let i=spores.length-1;i>=0;i--)if(spores[i].life<=0||spores[i].x<250)spores.splice(i,1)}
function updateControllers(){if(!CFG.mechanics.controllers)return;for(const c of actors){if(c.dead||c.kind!=='controller')continue;let target=actors.find(a=>!a.dead&&a!==c&&a.id===c.linkId);if(!target||Math.abs(target.x-c.x)>330){for(const old of actors)if(old.linkSource===c.id){old.linkSource=null;old.boost=1}target=actors.filter(a=>!a.dead&&a!==c&&a.kind!=='controller').sort((a,b)=>Math.abs(a.x-c.x)-Math.abs(b.x-c.x))[0];c.linkId=target?.id||null}if(target){target.linkSource=c.id;target.boost=Math.max(target.boost,1.55);c.linkPulse+=.12}}for(const a of actors)if(a.linkSource&&!actors.some(c=>!c.dead&&c.id===a.linkSource)){a.linkSource=null;a.boost=1}}
function updateTendrils(dt){if(!CFG.mechanics.tendrils)return;for(const t of tendrils){t.timer-=dt;if(t.timer<=0){t.active=.5;t.timer=2.2+Math.random()*1.4;t.cycle++;beep('tendril')}if(t.active>0){t.active-=dt;for(const a of actors){if(a.dead||a.tendrilTag===t.cycle)continue;if(Math.abs(a.x-t.x)<54&&Math.abs(a.y-terrainY(a.x))<95){a.tendrilTag=t.cycle;a.airborne=true;a.vy=-520;a.x-=32;floaters.push({x:a.x,y:a.y-65,text:'YEET!',life:.6})}}if(tank.flying&&Math.abs(tank.x-t.x)<58&&tank.y>terrainY(t.x)-115&&tank.vy>0){const key=`${t.x}-${t.cycle}`;if(tank.tendrilKey!==key){tank.tendrilKey=key;tank.vy=-Math.abs(tank.vy)*.62-190;tank.vx*=1.08;toast('TENDRIL BANK SHOT!',450);score+=75;impact(tank.x,tank.y,false,'#cb77ed')}}}}}
function updatePods(dt){if(!CFG.mechanics.pods)return;for(const p of pods){if(p.dead)continue;p.pulse+=dt*4;p.timer-=dt;if(p.timer<=0){const target=actors.find(a=>!a.dead&&!a.mutated&&['alienling','sporeling'].includes(a.kind)&&Math.abs(a.x-p.x)<520);if(target){mutateActor(target,'pod');target.x=p.x-55}p.timer=3.3+Math.random()*1.7}}}
function updateActor(a,dt){if(a.dead)return;a.phase+=dt*5.5;if(a.boost>1&&!a.linkSource)a.boost=Math.max(1,a.boost-dt*.8);if(a.airborne){a.vy+=GRAVITY*dt;a.y+=a.vy*dt;a.x-=a.speed*.85*a.boost*dt;const gy=terrainY(a.x)-28*a.scale;if(a.y>=gy){a.y=gy;a.vy=0;a.airborne=false}return}if(a.kind==='controller')a.x-=a.speed*.55*dt;else if(a.kind==='leaper'){a.x-=a.speed*a.boost*dt;a.jumpTimer-=dt;if(a.jumpTimer<=0&&a.x>420){a.airborne=true;a.vy=-480;a.jumpTimer=1.35+Math.random()*.7}}else a.x-=a.speed*a.boost*dt;a.y=terrainY(a.x)-28*a.scale;if(a.x<115){a.dead=true;resolved++;hurt(`${a.kind.toUpperCase()} ALIEN BROKE THROUGH!`)}}
function updateMission(dt){if(over||done)return;if(wave<0){between-=dt;if(between<=0)startWave();return}if(spawned<queue.length){spawnTimer-=dt;if(spawnTimer<=0)spawn();return}if(resolved<queue.length||actors.some(a=>!a.dead))return;if(wave<2){between+=dt;if(between>.95)startWave();return}finishTimer+=dt;if(finishTimer>.8)complete()}
function held(){return !aim||tank.flying?{x:tank.x,y:tank.y}:{x:aim.x,y:Math.min(aim.y,GROUND-40)}}
function throwTank(){if(!aim||tank.flying||!running)return;const dx=tank.x-aim.x,dy=tank.y-aim.y,p=Math.hypot(dx,dy);if(p<18){aim=null;return}const sc=Math.min(p,MAX_PULL)/p,b=steroidTimer>0?1.42:1,h=held();Object.assign(tank,{x:h.x,y:h.y,vx:dx*sc*F.throwScale*b,vy:dy*sc*F.throwScale*b,angular:Math.min(9,2+p/55),flying:true,resetTimer:0,bounced:false});tank.hitIds.clear();aim=null;hero.releaseTimer=.28;beep('throw')}
function updateTank(dt){if(!tank.flying)return;tank.vy+=GRAVITY*F.gravityMultiplier*dt;tank.x+=tank.vx*dt;tank.y+=tank.vy*dt;tank.angle+=tank.angular*dt;
for(const p of pods){if(p.dead||tank.hitIds.has(`pod-${p.x}`))continue;if(Math.hypot(tank.x-p.x,tank.y-(p.y-48))<70+F.collisionBonus){tank.hitIds.add(`pod-${p.x}`);p.hp--;impact(p.x,p.y-45,true,'#c767e5');if(p.hp<=0){p.dead=true;score+=500;specialKills++;floaters.push({x:p.x,y:p.y-100,text:'POD POPPED!',life:.9});beep('hit')}tank.vx*=.82;tank.vy*=.78}}
for(const a of actors){if(a.dead||tank.hitIds.has(a.id))continue;const r=(a.kind==='chonker'?72:a.kind==='controller'?55:47)+F.collisionBonus;if(Math.hypot(tank.x-a.x,tank.y-(a.y-6))<r){tank.hitIds.add(a.id);if(a.kind==='armored'&&a.armor>0){a.armor--;toast('ALIEN ARMOR CRACKED!',500);impact(a.x,a.y-20,true,'#b7e2ea');tank.vx*=-.22;tank.vy=-Math.abs(tank.vy)*.28-70;continue}kill(a,'vehicle');tank.vx*=F.impactX;tank.vy*=F.impactY}}
const gy=terrainY(tank.x)-22;if(tank.y>=gy){tank.y=gy;if(Math.abs(tank.vy)>155&&!tank.bounced){tank.vy*=F.bounceY;tank.vx*=F.bounceX;tank.bounced=true;impact(tank.x,tank.y+8,false,'#b97a67')}else{tank.vy=0;tank.vx*=Math.pow(.08,dt)}}if(tank.x<-450||tank.x>2350||(Math.abs(tank.vx)<12&&tank.y>=gy-1)){tank.resetTimer+=dt;if(tank.resetTimer>.58)resetTank()}else tank.resetTimer=0}
function complete(){if(done)return;done=true;running=false;const stars=1+(health===5?1:0)+(specialKills>=2?1:0);rStars.textContent='★'.repeat(stars)+'☆'.repeat(3-stars);rScore.textContent=score.toLocaleString();rCats.textContent=flattened;rMutations.textContent=mutations;rSpecial.textContent=specialKills;rDefense.textContent=health===5?'UNTOUCHED':`${health}/5 HEARTS`;toast(`${CFG.title} SECURED`,1100);beep('win');setTimeout(()=>winScreen.classList.add('visible'),800)}
function reset(){running=true;over=done=false;score=0;health=5;wave=-1;spawned=resolved=0;queue=[];spawnTimer=0;between=.35;finishTimer=0;elapsed=0;steroids=3;steroidTimer=0;cameraX=0;aim=null;shake=0;flattened=mutations=specialKills=0;sporeClock=1.1;actors.length=particles.length=floaters.length=0;Object.assign(hero,{armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0});resetTank();setupEnvironment();steroidButton.disabled=false;steroidCountEl.textContent='3 demo doses';hud();toast(CFG.title,950)}
function update(dt){if(!running){cameraX=updateCamera(cameraX,tank,aim,running,dt);updateJohnny(hero,tank,aim,running,dt);return}elapsed+=dt;if(steroidTimer>0)steroidTimer=Math.max(0,steroidTimer-dt);updateMission(dt);updateSpores(dt);updateControllers();updateTendrils(dt);updatePods(dt);for(const a of actors)updateActor(a,dt);updateTank(dt);for(const p of particles){p.life-=dt;p.vy+=410*dt;p.x+=p.vx*dt;p.y+=p.vy*dt}for(const f of floaters){f.life-=dt;f.y-=43*dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1);shake*=Math.pow(.003,dt);cameraX=updateCamera(cameraX,tank,aim,running,dt);updateJohnny(hero,tank,aim,running,dt);hud()}
function drawBg(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,level>=4?'#343047':'#49596b');sky.addColorStop(.5,level>=4?'#685066':'#75818a');sky.addColorStop(1,'#aa6e74');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.save();ctx.globalAlpha=.23;ctx.fillStyle='#d98cff';for(let i=0;i<14;i++){const x=(i*127+elapsed*12)%1450-80,y=80+(i*53)%360;ctx.beginPath();ctx.arc(x,y,3+(i%4),0,Math.PI*2);ctx.fill()}ctx.restore();ctx.fillStyle='#413c45';for(let i=-2;i<9;i++){const x=i*260-(cameraX*.05%260),h=90+((i*67)%130);ctx.beginPath();ctx.moveTo(x,GROUND);ctx.lineTo(x+70,GROUND-h);ctx.lineTo(x+150,GROUND-h*.7);ctx.lineTo(x+260,GROUND);ctx.closePath();ctx.fill()}ctx.fillStyle='#584650';ctx.fillRect(0,GROUND-28,W,28);ctx.fillStyle='#703c78';for(let x=500-(cameraX*.13%210);x<W+220;x+=210){ctx.beginPath();ctx.moveTo(x,GROUND-28);ctx.lineTo(x+14,GROUND-73-(level*5));ctx.lineTo(x+27,GROUND-28);ctx.fill();ctx.fillStyle='#b666c7';ctx.beginPath();ctx.arc(x+14,GROUND-70-(level*5),5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#703c78'}if(level===5){ctx.fillStyle='rgba(93,40,105,.35)';ctx.fillRect(0,GROUND-65,W,40)}}
function drawSpore(s){ctx.save();ctx.globalAlpha=.2+.34*(s.life/s.max);ctx.fillStyle='#d17af0';ctx.shadowColor='#d17af0';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='rgba(255,205,255,.58)';for(let i=0;i<7;i++){const a=s.pulse+i*.9+elapsed*.4;ctx.beginPath();ctx.arc(s.x+Math.cos(a)*s.r*.55,s.y+Math.sin(a)*s.r*.55,2.5,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawTendril(t){const y=terrainY(t.x);ctx.save();ctx.translate(t.x,y);ctx.strokeStyle=t.active>0?'#d56cf0':'#6e4776';ctx.lineWidth=t.active>0?10:6;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(0,14);ctx.quadraticCurveTo(-22,-22-Math.sin(elapsed*4+t.x)*8,5,-58-(t.active>0?45:0));ctx.stroke();ctx.fillStyle='#a75cba';ctx.beginPath();ctx.arc(5,-58-(t.active>0?45:0),8,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawPod(p){if(p.dead)return;ctx.save();ctx.translate(p.x,p.y);const pulse=1+Math.sin(p.pulse)*.04;ctx.scale(pulse,pulse);ctx.shadowColor='#d46df0';ctx.shadowBlur=18;ctx.fillStyle='#6f3d78';ctx.strokeStyle='#d886e8';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,-43,34,53,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#b96acb';ctx.beginPath();ctx.ellipse(0,-45,18,34,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#efbbff';ctx.beginPath();ctx.arc(-6,-58,5,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawActor(a){if(a.dead)return;ctx.save();ctx.translate(a.x,a.y+Math.sin(a.phase)*1.5);if(a.airborne)ctx.rotate(a.vy*.0003);ctx.scale(a.scale,a.scale);if(a.linkSource){ctx.save();ctx.strokeStyle='rgba(255,225,86,.75)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(3,-8,45,0,Math.PI*2);ctx.stroke();ctx.restore()}E.drawGround(ctx,{phase:a.phase,chonker:a.kind==='chonker',windup:a.kind==='controller'});if(a.kind==='alienling'||a.kind==='sporeling'){ctx.fillStyle='#ca70e0';ctx.beginPath();ctx.arc(20,-17,a.kind==='sporeling'?7:5,0,Math.PI*2);ctx.fill();if(a.kind==='sporeling'){ctx.strokeStyle='#eca5ff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(24,-20);ctx.lineTo(40,-34);ctx.stroke()}}if(a.kind==='controller'){ctx.save();ctx.shadowColor='#f4dc68';ctx.shadowBlur=14;ctx.fillStyle='#d2a8e7';ctx.beginPath();ctx.ellipse(-18,-48,30,21,0,Math.PI,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#f4dc68';ctx.lineWidth=3;for(let r=35;r<=55;r+=10){ctx.beginPath();ctx.arc(-16,-34,r,-1.35,-.15);ctx.stroke()}ctx.restore()}if(a.kind==='armored'){ctx.fillStyle='#687986';ctx.strokeStyle='#b9dce4';ctx.lineWidth=3;ctx.fillRect(-35,-20,65,23);ctx.strokeRect(-35,-20,65,23);if(a.armor<=0){ctx.strokeStyle='#f6d2c2';ctx.beginPath();ctx.moveTo(-10,-20);ctx.lineTo(0,-4);ctx.lineTo(12,-18);ctx.stroke()}}if(a.kind==='leaper'){ctx.strokeStyle='#90d3db';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-28,10);ctx.lineTo(-43,25);ctx.moveTo(24,10);ctx.lineTo(42,25);ctx.stroke()}ctx.restore()}
function render(){ctx.clearRect(0,0,W,H);ctx.save();if(shake>.4)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawBg();ctx.save();ctx.translate(-cameraX,0);for(const s of spores)drawSpore(s);for(const t of tendrils)drawTendril(t);for(const p of pods)drawPod(p);ctx.save();ctx.translate(24,3);ctx.translate(142,582);ctx.scale(.5,.5);ctx.translate(-142,-582);S.drawJohnny(ctx,hero,steroidTimer,elapsed);ctx.restore();for(const a of actors)drawActor(a);if(!tank.flying&&aim){const h=held();T.drawTank(ctx,{...tank,x:h.x,y:h.y,angle:-.08})}else T.drawTank(ctx,tank);if(aim&&!tank.flying){ctx.strokeStyle='#ffcf33';ctx.lineWidth=4;ctx.setLineDash([10,8]);ctx.beginPath();ctx.moveTo(tank.x,tank.y);ctx.lineTo(aim.x,aim.y);ctx.stroke();ctx.setLineDash([])}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=Math.max(0,f.life);ctx.fillStyle='#fff0a3';ctx.font='900 24px Impact,system-ui';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;ctx.textAlign='left';ctx.restore();ctx.restore()}
function frame(now){const dt=Math.min((now-last)/1000,.033);last=now;update(dt);render();requestAnimationFrame(frame)}
canvas.addEventListener('pointerdown',e=>{if(!running||tank.flying)return;const p=pointerToWorld(canvas,e,cameraX);if(Math.hypot(p.x-tank.x,p.y-tank.y)<130){aim=p;canvas.setPointerCapture?.(e.pointerId)}});
canvas.addEventListener('pointermove',e=>{if(!aim||tank.flying)return;const p=pointerToWorld(canvas,e,cameraX),dx=p.x-tank.x,dy=p.y-tank.y,l=Math.hypot(dx,dy);aim=l>MAX_PULL?{x:tank.x+dx/l*MAX_PULL,y:tank.y+dy/l*MAX_PULL}:p});
canvas.addEventListener('pointerup',throwTank);canvas.addEventListener('pointercancel',()=>aim=null);
steroidButton.addEventListener('click',()=>{if(!running||steroids<=0)return;steroids--;steroidTimer=12;steroidCountEl.textContent=steroids===1?'1 demo dose':`${steroids} demo doses`;steroidButton.disabled=steroids<=0;toast('UNREGULATED STRENGTH!');beep('power')});
muteButton.addEventListener('click',()=>{muted=!muted;muteButton.textContent=muted?'🔇':'🔊'});
$('start').addEventListener('click',()=>{titleScreen.classList.remove('visible');reset()});
$('restart').addEventListener('click',()=>{overScreen.classList.remove('visible');reset()});
$('replay').addEventListener('click',()=>{winScreen.classList.remove('visible');reset()});
hud();setupEnvironment();render();requestAnimationFrame(frame);
})();