(() => {
'use strict';
const S=window.JMShared,T=window.JMTankArt,F=window.JMWorld4Fighter,E=window.JMEnemyArt;
if(!S||!T||!F||!E) throw new Error('World 7 requires shared, tank, fighter, and enemy art modules');
const {W,H,GROUND,GRAVITY,TANK_HOME,MAX_PULL,pointerToWorld,updateCamera,updateJohnny}=S;
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),shell=document.getElementById('game-shell'),level=Number(shell.dataset.level||1);
const CFG={
  1:{title:'BOARDING ACTION',tag:'SURVIVE THE GRAVITY PULSES',mech:{gravity:true},waves:[['deckling','deckling','hover','deckling'],['deckling','warden','hover','deckling','brute'],['warden','hover','deckling','brute','shield','deckling']]},
  2:{title:'TRACTOR TROUBLE',tag:'THROW THROUGH THE BEAMS',mech:{gravity:true,tractor:true},waves:[['deckling','hover','deckling','warden'],['shield','deckling','hover','brute','deckling'],['warden','shield','hover','brute','deckling','hover']]},
  3:{title:'CONVEYOR CARNAGE',tag:'FIGHT THE MOVING DECK',mech:{conveyor:true},waves:[['deckling','deckling','warden','hover'],['brute','deckling','shield','warden','deckling'],['shield','brute','hover','warden','deckling','brute']]},
  4:{title:'REACTOR RUN',tag:'MAKE THE CELLS WORK FOR YOU',mech:{reactor:true,tractor:true},waves:[['deckling','hover','warden','deckling'],['shield','brute','deckling','hover','warden'],['brute','shield','warden','hover','brute','deckling']]},
  5:{title:'COMMAND CORRIDOR',tag:'THE WHOLE SHIP WANTS YOU GONE',mech:{gravity:true,tractor:true,conveyor:true,reactor:true},waves:[['warden','deckling','hover','shield'],['brute','warden','hover','deckling','shield'],['shield','brute','warden','hover','brute','deckling','warden']]}
}[level];
if(!CFG) throw new Error(`Unknown mothership level ${level}`);
const $=id=>document.getElementById(id);
const scoreEl=$('score'),healthEl=$('health'),waveEl=$('wave'),remainEl=$('remaining'),gravityEl=$('gravity-status'),deckEl=$('deck-status'),steroidButton=$('steroids'),steroidCountEl=$('steroid-count'),muteButton=$('mute'),titleScreen=$('title-screen'),overScreen=$('game-over'),winScreen=$('mission-complete'),finalScoreEl=$('final-score'),toastEl=$('toast'),rStars=$('result-stars'),rScore=$('result-score'),rCats=$('result-cats'),rSpecial=$('result-special'),rDefense=$('result-defense');
let last=performance.now(),running=false,over=false,done=false,score=0,health = window.JMPowerUps?.getStartingState().health ?? 5,wave=-1,spawned=0,resolved=0,queue=[],spawnTimer=0,between=0,finishTimer=0,elapsed=0,muted=false,audio=null,steroids = window.JMPowerUps?.getStartingState().steroids ?? 3,steroidTimer = window.JMPowerUps?.getStartingState().steroidTimer ?? 0,cameraX=0,aim=null,shake=0,toastTimer=null,kills=0,specialKills=0;
let gravityMode=1,gravityClock=2.8,conveyorDir=1,conveyorClock=3.6,beamPhase=0;
const actors=[],reactors=[],particles=[],floaters=[];
const hero={armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0};
const tank={x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,resetTimer:0,bounced:false,hitIds:new Set()};
function toast(t,d=900){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),d)}
function beep(type='hit'){if(muted)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime,m={throw:[96,52,.1],hit:[82,44,.09],gravity:[230,110,.2],beam:[420,170,.16],reactor:[120,620,.28],hurt:[120,70,.2],win:[330,880,.45],power:[160,420,.25]}[type]||[120,80,.1];o.type=type==='reactor'?'sawtooth':'square';o.frequency.setValueAtTime(m[0],n);o.frequency.exponentialRampToValueAtTime(m[1],n+m[2]);g.gain.setValueAtTime(.05,n);g.gain.exponentialRampToValueAtTime(.001,n+m[2]);o.connect(g).connect(audio.destination);o.start(n);o.stop(n+m[2])}catch{}}
function impact(x,y,strong=false,c='#72e5ff'){for(let i=0;i<(strong?24:11);i++){const a=Math.random()*Math.PI*2,s=60+Math.random()*(strong?300:150);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-80,life:.35+Math.random()*.4,max:.75,size:2+Math.random()*7,c})}shake=Math.max(shake,strong?16:7)}
function hud(){scoreEl.textContent=String(score).padStart(6,'0');healthEl.textContent=Array.from({length:5},(_,i)=>i<health?'♥':'♡').join(' ');waveEl.textContent=`${Math.max(1,wave+1)}/3`;remainEl.textContent=wave<0?'INCOMING':String(Math.max(0,queue.length-resolved));gravityEl.textContent=CFG.mech.gravity?(gravityMode<.8?'LOW':gravityMode>1.1?'HEAVY':'NORMAL'):'STABLE';deckEl.textContent=CFG.mech.conveyor?(conveyorDir>0?'← PORT':'STARBOARD →'):(CFG.mech.tractor?'TRACTOR ONLINE':'LOCKED')}
function resetTank(){Object.assign(tank,{x:TANK_HOME.x,y:TANK_HOME.y,vx:0,vy:0,angle:0,angular:0,flying:false,resetTimer:0,bounced:false});tank.hitIds.clear();aim=null}
function terrainY(){return GROUND-18}
function setupEnvironment(){reactors.length=0;if(CFG.mech.reactor){for(const x of level===5?[760,1230,1730]:[820,1420,1960])reactors.push({x,y:GROUND-60,hp:1,dead:false,pulse:Math.random()*6.2})}}
function actor(kind,index){const x=930+index*145+Math.random()*70;return{id:`${wave}-${index}-${Math.random()}`,kind,x,y:terrainY()-28,vy:0,airborne:kind==='hover',speed:kind==='warden'?44:kind==='brute'?38:kind==='shield'?48:kind==='hover'?54:58,scale:kind==='brute'?1.35:kind==='warden'?1.02:kind==='shield'?1.05:kind==='hover'?.86:.8,dead:false,phase:Math.random()*6.2,hp:kind==='brute'?2:1,shieldFlash:0};}
function startWave(){wave++;queue=CFG.waves[wave].slice();spawned=resolved=0;spawnTimer=.25;between=0;finishTimer=0;toast(`WAVE ${wave+1}: ${CFG.tag}`,1100);hud()}
function hurt(t){if(over||done)return;health = window.JMPowerUps?.takeDamage(health) ?? (health - 1);shake=20;impact(170,GROUND-85,true,'#ffad7d');toast(t,900);beep('hurt');hud();if(health<=0){running=false;over=true;finalScoreEl.textContent=`Score: ${score.toLocaleString()} · Ship hostiles flattened: ${kills}`;overScreen.classList.add('visible')}}
function kill(a,why='vehicle'){if(a.dead)return;a.dead=true;resolved++;kills++;if(a.kind!=='deckling')specialKills++;score+=a.kind==='brute'?550:a.kind==='warden'?500:a.kind==='shield'?450:a.kind==='hover'?420:350;impact(a.x,a.y-18,true,a.kind==='warden'?'#ffe36e':'#72e5ff');floaters.push({x:a.x,y:a.y-75,text:why==='reactor'?'REACTOR CHAIN!':'WHAM!',life:.8});if(why==='reactor')score+=250;beep('hit');hud()}
function spawn(){actors.push(actor(queue[spawned],spawned));spawned++;spawnTimer=.55+Math.random()*.25}
function updateGravity(dt){if(!CFG.mech.gravity){gravityMode=1;return}gravityClock-=dt;if(gravityClock<=0){gravityMode=gravityMode===1?(Math.random()<.5?.55:1.35):1;gravityClock=gravityMode===1?2.4:2.2;toast(gravityMode<.8?'GRAVITY FIELD: LOW!':gravityMode>1.1?'GRAVITY FIELD: HEAVY!':'GRAVITY NORMALIZED',800);beep('gravity');hud()}}
function updateConveyor(dt){if(!CFG.mech.conveyor)return;conveyorClock-=dt;if(conveyorClock<=0){conveyorDir*=-1;conveyorClock=3.8;toast(conveyorDir>0?'DECK MOVING PORT!':'DECK MOVING STARBOARD!',750);hud()}}
function tractorCenters(){return level===5?[720,1320,1880]:[850,1500]}
function tractorForce(x){if(!CFG.mech.tractor)return 0;let best=0;for(const bx of tractorCenters()){const d=bx-x;if(Math.abs(d)<190){const f=d/190;best+=f*210}}return best}
function updateActors(dt){for(const a of actors){if(a.dead)continue;a.phase+=dt*5;a.shieldFlash=Math.max(0,a.shieldFlash-dt);const conveyor=CFG.mech.conveyor?conveyorDir*42:0;if(a.kind==='hover'){a.y=GROUND-160+Math.sin(elapsed*3+a.phase)*55;a.x-=Math.max(16,a.speed-conveyor*.25)*dt}else{a.x-=Math.max(14,a.speed-conveyor)*dt;a.y=terrainY()-28*a.scale}if(CFG.mech.tractor){const tf=tractorForce(a.x);a.x+=tf*.08*dt;if(a.kind!=='hover'&&Math.abs(tf)>80)a.y-=Math.min(50,Math.abs(tf)*.17)}if(a.x<112){a.dead=true;resolved++;hurt(`${a.kind.toUpperCase()} ALIEN BREACHED JOHNNY'S POSITION!`)}}}
function updateReactors(dt){for(const r of reactors)r.pulse+=dt*4}
function explodeReactor(r){if(r.dead)return;r.dead=true;specialKills++;score+=600;impact(r.x,r.y-20,true,'#ff7df2');beep('reactor');toast('REACTOR CELL CHAIN REACTION!',850);for(const a of actors){if(!a.dead&&Math.abs(a.x-r.x)<250)kill(a,'reactor')}if(tank.flying&&Math.abs(tank.x-r.x)<280){tank.vx*=1.18;tank.vy-=220}}
function updateMission(dt){if(over||done)return;if(wave<0){between-=dt;if(between<=0)startWave();return}if(spawned<queue.length){spawnTimer-=dt;if(spawnTimer<=0)spawn();return}if(resolved<queue.length||actors.some(a=>!a.dead))return;if(wave<2){between+=dt;if(between>.95)startWave();return}finishTimer+=dt;if(finishTimer>.85)complete()}
function held(){return !aim||tank.flying?{x:tank.x,y:tank.y}:{x:aim.x,y:Math.min(aim.y,GROUND-40)}}
function throwTank(){if(!aim||tank.flying||!running)return;const dx=tank.x-aim.x,dy=tank.y-aim.y,p=Math.hypot(dx,dy);if(p<18){aim=null;return}const sc=Math.min(p,MAX_PULL)/p,b=(steroidTimer > 0 ? 1.42 : 1) * (window.JMPowerUps?.getThrowMultiplier() ?? 1),h=held();Object.assign(tank,{x:h.x,y:h.y,vx:dx*sc*F.throwScale*b,vy:dy*sc*F.throwScale*b,angular:Math.min(9,2+p/55),flying:true,resetTimer:0,bounced:false});tank.hitIds.clear();aim=null;hero.releaseTimer=.28;beep('throw')}
function updateTank(dt){if(!tank.flying)return;const g=GRAVITY*F.gravityMultiplier*gravityMode;tank.vy+=g*dt;if(CFG.mech.tractor){const tf=tractorForce(tank.x);tank.vx+=tf*dt;tank.vy-=Math.abs(tf)*.19*dt;beamPhase+=dt*7}tank.x+=tank.vx*dt;tank.y+=tank.vy*dt;tank.angle+=tank.angular*dt;
for(const r of reactors){if(r.dead||tank.hitIds.has(`r-${r.x}`))continue;if(Math.hypot(tank.x-r.x,tank.y-(r.y-45))<64+F.collisionBonus){tank.hitIds.add(`r-${r.x}`);explodeReactor(r);tank.vx*=.84;tank.vy*=.74}}
for(const a of actors){if(a.dead||tank.hitIds.has(a.id))continue;const rr=(a.kind==='brute'?70:a.kind==='hover'?50:48)+F.collisionBonus;if(Math.hypot(tank.x-a.x,tank.y-(a.y-8))<rr){if(a.kind==='shield'&&tank.vy<80&&tank.x<a.x){a.shieldFlash=.25;toast('ALIEN SHIELD DEFLECTED IT!',450);tank.vx*=-.34;tank.vy=-Math.abs(tank.vy)*.3-70;tank.hitIds.add(a.id);continue}a.hp--;tank.hitIds.add(a.id);if(a.hp<=0)kill(a);else{impact(a.x,a.y-20,true,'#f0b66a');floaters.push({x:a.x,y:a.y-70,text:'ARMOR CRACKED!',life:.7});tank.vx*=.76;tank.vy*=.8}}}
if(tank.y>=GROUND-22){tank.y=GROUND-22;if(Math.abs(tank.vy)>150&&!tank.bounced){tank.vy*=F.bounceY;tank.vx*=F.bounceX;tank.bounced=true;impact(tank.x,tank.y+8)}else{tank.vy=0;const belt=CFG.mech.conveyor?conveyorDir*55:0;tank.vx=tank.vx*Math.pow(.08,dt)+belt*dt}}
const grounded=tank.y>=GROUND-23&&Math.abs(tank.vy)<1;if(tank.x<-450||tank.x>2450||(grounded&&(CFG.mech.conveyor||Math.abs(tank.vx)<13))){tank.resetTimer+=dt;if(tank.resetTimer>.62)resetTank()}else tank.resetTimer=0}
function update(dt){if(!running){cameraX=updateCamera(cameraX,tank,aim,running,dt);updateJohnny(hero,tank,aim,running,dt);return}elapsed+=dt;if(steroidTimer>0)steroidTimer=Math.max(0,steroidTimer-dt);updateGravity(dt);updateConveyor(dt);updateReactors(dt);updateActors(dt);updateTank(dt);updateMission(dt);for(const p of particles){p.life-=dt;p.vy+=430*dt;p.x+=p.vx*dt;p.y+=p.vy*dt}for(const f of floaters){f.life-=dt;f.y-=45*dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(let i=floaters.length-1;i>=0;i--)if(floaters[i].life<=0)floaters.splice(i,1);shake*=Math.pow(.002,dt);cameraX=updateCamera(cameraX,tank,aim,running,dt);updateJohnny(hero,tank,aim,running,dt);hud()}
function drawShip(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#080b19');g.addColorStop(.55,'#111833');g.addColorStop(1,'#1d2541');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#252d4a';ctx.fillRect(0,GROUND-35,W,35);ctx.strokeStyle='#48577e';ctx.lineWidth=3;for(let x=0;x<W;x+=120){ctx.beginPath();ctx.moveTo(x,GROUND-35);ctx.lineTo(x+42,GROUND);ctx.stroke()}ctx.globalAlpha=.55;for(let i=0;i<7;i++){const x=90+i*205;ctx.fillStyle=i%2?'#53d3ff':'#ba65ef';ctx.fillRect(x,85,6,290);ctx.fillRect(x+12,85,2,290)}ctx.globalAlpha=1;ctx.fillStyle='#0a0f20';ctx.fillRect(0,0,W,64);ctx.fillStyle='#69e5ff';ctx.font='900 18px system-ui';ctx.fillText(`MOTHERSHIP DECK ${level} · ${CFG.title}`,28,39);if(level>=4){ctx.save();ctx.globalAlpha=.5;ctx.fillStyle='#ff58c8';ctx.beginPath();ctx.arc(1110,180,85,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.7;ctx.fillStyle='#160d2b';ctx.beginPath();ctx.arc(1110,180,61,0,Math.PI*2);ctx.fill();ctx.restore()}}
function drawMechanics(){if(CFG.mech.tractor){for(const x of tractorCenters()){const pulse=.35+.2*Math.sin(elapsed*7+x);ctx.save();ctx.globalAlpha=pulse;const grad=ctx.createLinearGradient(x-100,0,x+100,0);grad.addColorStop(0,'rgba(80,210,255,0)');grad.addColorStop(.5,'rgba(80,210,255,.55)');grad.addColorStop(1,'rgba(80,210,255,0)');ctx.fillStyle=grad;ctx.fillRect(x-120,78,240,GROUND-100);ctx.strokeStyle='#75e5ff';ctx.lineWidth=3;ctx.strokeRect(x-82,78,164,GROUND-100);ctx.restore()}}
if(CFG.mech.conveyor){ctx.save();ctx.fillStyle='#111725';ctx.fillRect(0,GROUND-45,2400,45);ctx.strokeStyle='#e3bd58';ctx.lineWidth=5;const off=(elapsed*80*conveyorDir)%80;for(let x=-100+off;x<2500;x+=80){ctx.beginPath();ctx.moveTo(x,GROUND-39);ctx.lineTo(x+34*conveyorDir,GROUND-19);ctx.lineTo(x,GROUND-2);ctx.stroke()}ctx.restore()}
for(const r of reactors){if(r.dead)continue;ctx.save();ctx.translate(r.x,r.y);ctx.shadowColor='#ff73dd';ctx.shadowBlur=18+Math.sin(r.pulse)*8;ctx.fillStyle='#52245f';ctx.fillRect(-25,-72,50,72);ctx.fillStyle='#ff6ee1';ctx.fillRect(-14,-59,28,43);ctx.strokeStyle='#ffc0f1';ctx.lineWidth=3;ctx.strokeRect(-25,-72,50,72);ctx.restore()}}
function drawActor(a){if(a.dead)return;ctx.save();ctx.translate(a.x,a.y);ctx.scale(a.scale,a.scale);if(a.kind==='hover')ctx.translate(0,-18);E.drawGround(ctx,{phase:a.phase,windup:a.kind==='warden'});if(a.kind==='warden'){ctx.fillStyle='#f4d766';ctx.fillRect(-28,-72,56,10);ctx.fillStyle='#1b2130';ctx.fillRect(-17,-78,34,7)}if(a.kind==='shield'){ctx.save();ctx.translate(-42,-32);ctx.fillStyle=a.shieldFlash>0?'#ffffff':'#75dffc';ctx.strokeStyle='#d6f8ff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-10,-34);ctx.lineTo(27,-46);ctx.lineTo(39,27);ctx.lineTo(-9,42);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}if(a.kind==='brute'){ctx.fillStyle='#bf6ee7';ctx.beginPath();ctx.arc(0,-25,12,0,Math.PI*2);ctx.fill()}if(a.kind==='hover'){ctx.strokeStyle='#8ff3ff';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-30,8);ctx.quadraticCurveTo(0,42,30,8);ctx.stroke()}ctx.restore()}
function drawTrajectory(){if(!aim||tank.flying)return;const dx=tank.x-aim.x,dy=tank.y-aim.y,p=Math.hypot(dx,dy);if(p<1)return;const sc=Math.min(p,MAX_PULL)/p,b=(steroidTimer > 0 ? 1.42 : 1) * (window.JMPowerUps?.getThrowMultiplier() ?? 1),h=held(),vx=dx*sc*F.throwScale*b,vy=dy*sc*F.throwScale*b,g=GRAVITY*F.gravityMultiplier*gravityMode;ctx.save();ctx.strokeStyle='#ffcf33';ctx.lineWidth=3;ctx.setLineDash([7,7]);ctx.beginPath();ctx.moveTo(h.x,h.y);let x=h.x,y=h.y,vxx=vx,vyy=vy;const step=.07;for(let i=0;i<34;i++){if(CFG.mech.tractor){const tf=tractorForce(x);vxx+=tf*step;vyy-=Math.abs(tf)*.19*step}vyy+=g*step;x+=vxx*step;y+=vyy*step;if(y>GROUND-22||x>2450)break;ctx.lineTo(x,y)}ctx.stroke();ctx.restore()}
function render(){ctx.clearRect(0,0,W,H);ctx.save();if(shake>.4)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawShip();ctx.save();ctx.translate(-cameraX,0);drawMechanics();ctx.save();ctx.translate(24,3);ctx.translate(142,582);ctx.scale(.5,.5);ctx.translate(-142,-582);S.drawJohnny(ctx,hero,steroidTimer,elapsed);ctx.restore();for(const a of actors)drawActor(a);if(!tank.flying&&aim){const h=held();T.drawTank(ctx,{...tank,x:h.x,y:h.y,angle:-.08})}else T.drawTank(ctx,tank);drawTrajectory();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=Math.max(0,f.life);ctx.fillStyle='#fff0a3';ctx.font='900 24px Impact,system-ui';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;ctx.restore();ctx.restore()}
function complete(){if(done)return;done=true;running=false;const stars=1+(health>=3?1:0)+(specialKills>=3?1:0);rStars.textContent='★'.repeat(stars)+'☆'.repeat(3-stars);rScore.textContent=score.toLocaleString();rCats.textContent=kills;rSpecial.textContent=specialKills;rDefense.textContent=health===5?'UNTOUCHED':`${health}/5 HEARTS`;beep('win');setTimeout(()=>winScreen.classList.add('visible'),700)}
function reset(){running=true;over=done=false;score=0;health = window.JMPowerUps?.getStartingState().health ?? 5;wave=-1;spawned=resolved=0;queue=[];spawnTimer=0;between=.25;finishTimer=0;elapsed=0;steroids = window.JMPowerUps?.getStartingState().steroids ?? 3;steroidTimer = window.JMPowerUps?.getStartingState().steroidTimer ?? 0;cameraX=0;aim=null;shake=0;kills=specialKills=0;gravityMode=1;gravityClock=2.8;conveyorDir=1;conveyorClock=3.6;actors.length=particles.length=floaters.length=0;setupEnvironment();resetTank();Object.assign(hero,{armAngle:-.75,releaseTimer:0,torsoLean:0,squat:0,catchPose:0});steroidButton.disabled=false;steroidCountEl.textContent = window.JMPowerUps?.doseLabel(steroids) ?? '3 doses';hud();toast(`${CFG.title}: ${CFG.tag}`,1800)}
function frame(now){const dt=Math.min((now-last)/1000,.033);last=now;update(dt);render();requestAnimationFrame(frame)}
canvas.addEventListener('pointerdown',e=>{if(!running||tank.flying)return;const p=pointerToWorld(canvas,e,cameraX);if(Math.hypot(p.x-tank.x,p.y-tank.y)<145){aim=p;canvas.setPointerCapture?.(e.pointerId)}});
canvas.addEventListener('pointermove',e=>{if(!aim||tank.flying)return;const p=pointerToWorld(canvas,e,cameraX),dx=p.x-tank.x,dy=p.y-tank.y,l=Math.hypot(dx,dy);aim=l>MAX_PULL?{x:tank.x+dx/l*MAX_PULL,y:tank.y+dy/l*MAX_PULL}:p});
canvas.addEventListener('pointerup',throwTank);canvas.addEventListener('pointercancel',()=>aim=null);
steroidButton.addEventListener('click',()=>{if(!running||steroids<=0)return;steroids--;steroidTimer=12;steroidCountEl.textContent=steroids===1?'1 dose':`${steroids} doses`;steroidButton.disabled=steroids<=0;toast('UNREGULATED STRENGTH!');beep('power')});
muteButton.addEventListener('click',()=>{muted=!muted;muteButton.textContent=muted?'🔇':'🔊'});
$('start').addEventListener('click',()=>{titleScreen.classList.remove('visible');reset()});
$('restart').addEventListener('click',()=>{overScreen.classList.remove('visible');reset()});
$('replay').addEventListener('click',()=>{winScreen.classList.remove('visible');reset()});
hud();setupEnvironment();render();requestAnimationFrame(frame);
})();